### ISSUE TITLE
Binary file support

### ISSUE THREAD

**Issue by DirtyHairy** [justwatchcom/gopass#102]
The ability to store arbitrary binary files in the gopass store would be an awesome extension. The docs state "almost done" on this --- what's the status on this? Depending on what is still to do, I am interested in contributing :smirk:

**Comment by dominikschulz** [comment]
Sorry for the delay. We built something but had to pull it from the release due to some inconsistencies. We plan to work on this "soon". No precise ETA, sorry.

**Comment by bumi** [comment]
This would be a super helpful extension, I am also happy to contribute. Is there already some code to build on?

**Comment by dominikschulz** [comment]
Closed by #136

**Comment by tetrodoxin** [comment]
Just a short question:
What was the actual reason to deprecate this feature?
