### ISSUE TITLE
Initiate search instead of displaying "Error: Entry is not in the password store"

### ISSUE THREAD

**Issue by adius** [justwatchcom/gopass#106]
If you execute `gopass asdf.com` but `asdf.com` is not in the password store it should instead execute `gopass search asdf.com`.

(And maybe print an error message if then still nothing was found, as `gopass search` normally doesn't do anything if nothing was found. This, however, would be slightly confusing.)

**Comment by ParagonDefect** [comment]
This needs to be reverted. Retrieving secrets needs to be an explicit operation by default, if you want to search then use the search feature.

**Comment by dominikschulz** [comment]
@ParagonDefect You're are a little bit late to this. This has been merged years ago.

But we could add a config option turn it off, I guess.
