### ISSUE TITLE
gopass copies entire file into clipboard

### ISSUE THREAD

**Issue by cndreisbach** [justwatchcom/gopass#11]
When you run `pass -c <filename>`, pass's behavior is to copy the first line of the file, allowing you to get the password easily while using the rest of the file in a freeform fashion. gopass seems to copy the whole contents of the file, which makes it hard to use multiple lines for things like login and URL.

**Comment by metalmatze** [comment]
I don't think it's intended to be like this, right. We should fix that @dominikschulz, right? I will do that tomorrow, if there are no objections.
