### ISSUE TITLE
Storing structured files

### ISSUE THREAD

**Issue by bumi** [justwatchcom/gopass#112]
The readme mentions "Storing structured files" as ToDo. Because I have not found any related issue I am opening this one. 
Are there already plans on how to support structured data like credit card information and still be compatible with `pass`? 

Storing more structured information is an extension I am currently looking for, not sure if my go skills will be good enough but would be happy to look into it.

**Comment by dominikschulz** [comment]
The general idea is to support some kind of structured data, e.g. yaml, inside secrets. Of course you can do that right now, but the plan is to give easy read/write access to parts of these files so you can do e.g. `gopass my/credit/card number` on a file like

```
---
name: John Doe
Number: 1234 5678 9012 1234
CV2: 123
```

And get an output like `1234 5678 9012 1234`. Also this should support updates like `gopass insert my/credit/card name`.

In a regular `pass` you would just get the YAML content.

We will try to provide a timeline soon.

**Comment by dominikschulz** [comment]
Implemented in #125
