### ISSUE TITLE
Adding addition information at generate

### ISSUE THREAD

**Issue by i1skn** [justwatchcom/gopass#116]
Hello, I was thinking would it be nice to have an ability to add info, like `login` or `url` just after you generate a new password? 

For example:
```
gopass generate example.com
How long should the password be? [24]:
The generated password for example.com is:
xxxxxxx
```
Usually here, if a user wants to add more info (s)he needs to type `gopass edit example.com`, but
what if gopass will ask the user immediately about that?
```
Do you want to add more data?  [y/N]?
```
If yes - do `gopass edit example.com`, if no - do nothing.

**Comment by dominikschulz** [comment]
This could play nice with structured secrets #114 and templates #1.

But I want to think twice about the UX.

**Comment by i1skn** [comment]
@dominikschulz Cool, I would be happy to help to implement this feature!
