### ISSUE TITLE
gopass does not follow symlink to password-store

### ISSUE THREAD

**Issue by matze** [justwatchcom/gopass#12]
On my systems `$HOME/.password-store` is a symlink which works just fine with `pass` but not `gopass`.

**Comment by rsanders** [comment]
I have the same problem.  This is a very useful thing to do if you're storing your password store on Dropbox.

**Comment by dominikschulz** [comment]
We decided not to allow symlinks within the path to the password store, but with gopass you can change the path to the password store in the config, see https://github.com/justwatchcom/gopass#storing-and-syncing-your-password-store-with-google-drivedropbox

But we're open to an discussion if this artificial limitation makes sense or not.

**Comment by matze** [comment]
That limitation makes no sense when you state that you "try hard to maintain full pass compatibility" and promise that I am "free to switch back and forth between pass and gopass for now." 

> But we're open to an discussion if this artificial limitation makes sense or not.

You could start the discussion explaining why you decided to break compatibility by not allowing symlinks ;-)

**Comment by danmilon** [comment]
Got hit by this too. I dont see why we need to treat symlinks specially.

**Comment by dominikschulz** [comment]
Fair enough. We *try* to maintain compatibility *for now*. This doesn't mean we'll support every use-case or that switching is completely effortless. Also we already plan for breaking that compatibility in the future.

One reason for not allowing symlinks is that it introduces some additional complexity we didn't want to deal with. After all you don't need symlinks to change the path to the store. You just set the path in the config.

That being said, if you come up with a good reason why we should support symlinks we'll probably accept a PR that lifts that limitation.

**Comment by matze** [comment]
> One reason for not allowing symlinks is that it introduces some additional complexity we didn't want to deal with.

Aren't you introducing additional complexity by [actually handling the symlink case](https://github.com/justwatchcom/gopass/blob/a6f88e079be193f82779abb49d89c90442c91edb/password/store.go#L162-L164)?

> That being said, if you come up with a good reason why we should support symlinks we'll probably accept a PR that lifts that limitation.

I already stated my reason which would be full `pass` compatibility. But since this is my only reason and you do not accept it you can close this issue as well.

**Comment by dominikschulz** [comment]
This was fixed by merging #41
