### ISSUE TITLE
reencrypting via init doesn't work

### ISSUE THREAD

**Issue by bonds** [justwatchcom/gopass#120]
I wanted to reencrypt my passwords using a new key. I tried with gopass and I got an error:

````
❯❯❯ gopass init B5873729329392932933blahblahgpgid

Error: Store is already initialized
````
I tried with ````pass```` and it worked just fine.

I'm running OpenBSD 6.1-stable amd64, fish shell.

````
gopass HEAD (n/a ) go1.8
````

Not sure when I built it using ````go get```` I'm sorry to say, and that version doesn't help much...but there it is.

**Comment by dominikschulz** [comment]
This is intentional since the behavior of `pass` regarding `init` felt especially confusing.

Please use `gopass recipients add` followed by `gopass recipients remove` instead.

**Comment by bonds** [comment]
make sense, thanks!
