### ISSUE TITLE
`pass` compatibility broken : handling sub gpg-id files

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#137]
## Context 

Using `gopass` latest version 
```
mfronton@lilbox:~$ go get -u github.com/justwatchcom/gopass
mfronton@lilbox:~$ gopass version
gopass HEAD (n/a ) go1.8.3
mfronton@lilbox:/opt/go/path/src/github.com/justwatchcom/gopass$ git describe
v1.1.2-2-g8e31f46
mfronton@lilbox:~$ rm -rf .config/gopass/
```

Using `pass` latest version
```
mfronton@lilbox:~$ git clone https://git.zx2c4.com/password-store /tmp/password-store
mfronton@lilbox:~$ cd /tmp/password-store
mfronton@lilbox:/tmp/password-store$ sudo make install
mfronton@lilbox:/tmp/password-store$ pass --version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.7.1                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================
```
With only one pubkey in my gpg db 

```
mfronton@lilbox:~$ gpg --list-key
/home/mfronton/.gnupg/pubring.gpg
---------------------------------
pub   4096R/A809234F 2016-09-14
uid                  Matthieu Fronton <m@tthieu.fr>
sub   4096R/81FD1581 2016-09-14
```
#### Using pass

From a `pass` store :

```
mfronton@lilbox:~$ rm -rf ~/.config/gopass/ ~/.password-store

mfronton@lilbox:~$ pass init m@tthieu.fr
mfronton@lilbox:~$ cd ~/.password-store

mfronton@lilbox:~$ pass git init
mfronton@lilbox:~$ git log --oneline
```

:white_check_mark: store and git initialized

```
mfronton@lilbox:~$ pass generate -n Project-A/admin 10
mfronton@lilbox:~$ git log --oneline
```

:white_check_mark: admin.gpg added to Project-A/ using root gpg-id identities file

```
mfronton@lilbox:~$ pass generate -n Project-B/admin 10
mfronton@lilbox:~$ git log --oneline
```

:white_check_mark: admin.gpg added to Project-B/ using root gpg-id identities file

```
mfronton@lilbox:~$ pass init -p Project-B $(cat ~/.password-store/Project-B/.gpg-id 2>/dev/null) m@tthieu.fr 
mfronton@lilbox:~$ git log --oneline
```

:white_check_mark: new .gpg-id file created with "m@tthieu.fr" identity 

```
mfronton@lilbox:~Ok: $ pass generate -n Project-B/ops 10
mfronton@lilbox:~$ git log --oneline
```

:white_check_mark: ops.gpg added to Project-B/ using its own gpg-id identities file

```
mfronton@lilbox:~$ pass init -p Project-B $(cat ~/.password-store/Project-B/.gpg-id 2>/dev/null) null@missing.com
mfronton@lilbox:~$ git log --oneline
```
:white_check_mark: new .gpg-id file created with "null@missing.com" identity 

```
pass generate -n Project-B/dev 10
git log --oneline  
```
:white_check_mark: the `generate` **failed** I don't have any public key for null@missing.com, and there is **no git commit** 

#### Using gopass

Lets repeat the latest `generate` using `gopass` 

```
gopass generate -n Project-B/dev 10
git log --oneline
```
:red_circle: the `generate` does **not fail** and the change **is commited** (and pushed) 

_**=> the compatibility promise with `pass` is broken here**_

## What I Expected

I expected `gopass` to use the first `gpg-id` found, searching from destination up to root folder.

For example if trying to do something like `gopass insert /Project-B/teamdev/wiki/secret` it should search for the first identities file in this order :
- /Project-B/teamdev/wiki/gpg-id 
- /Project-B/teamdev/gpg-id 
- /Project-B/gpg-id 
- /gpg-id 

## Further Notes

If I add a fake identity to root gpg-id

```
mfronton@lilbox:~$ pass init $(cat ~/.password-store/.gpg-id 2>/dev/null) null@missing.com
Password store initialized for m@tthieu.fr, null@missing.com
[master c0c2252] Set GPG id to m@tthieu.fr, null@missing.com.
 1 file changed, 1 insertion(+)
``` 

Then `pass` and `gopass` behave the same way

``` 
mfronton@lilbox:~$ pass generate -n Project-A/dev3 10
gpg: null@missing.com: skipped: No public key
gpg: [stdin]: encryption failed: No public key
Password encryption aborted.

mfronton@lilbox:~$ gopass generate -n Project-A/dev3 10
gpg: null@missing.com: skipped: No public key
gpg: [stdin]: encryption failed: No public key

Error: Failed to encrypt
``` 

That's why I believe this issue is limited to sub gpg-id files

**Comment by dominikschulz** [comment]
Thanks for reporting this.

We do not plan on supporting sub gpg-id files right now. We suggest you use the mount feature of `gopass` for that.

It is a common misconception that we commit to 100% `pass` compatibility forever. This is not true. Establishing `pass` compatibility was a major development milestone during the development of `gopass`. Since then both projects have moved on and some feature can and will diverge from each other. We try not to deliberately break `pass` compatibility without good reasons, but we also don't follow the development of `pass` anymore, so we won't adjust `gopass` to match any feature/change that may happen in `pass`.

If someone is willing and able to submit a proper PR that implements this in sane way, we'll most probably merge this.

**Comment by frntn** [comment]
Seems legit !

I do agree that `gopass` have to live its own life now.
Do you know until which `pass` version both project were 100% compatible ? 

(Mounts are the best idea you guys had ;))

**Comment by dominikschulz** [comment]
1.6.5. We should have put that in the docs.

**Comment by frntn** [comment]
Searching for the latest `pass` version I should allow my team to use with our `gopass` store I retried this on 1.6.5 which actually handles multiple identities in subfolder.

I have automated the workflow describe in the issue, and tried it against each pass release from 1.6.5 (released 2015-01-28) back to 1.4.2 (released in 2012-10-18) which is the first one not able to handle multiple identities.

I prefer and believe in `gopass` so I think I'll just forbid `pass` usage to prevent store corruption.

Thanks.

**Comment by dominikschulz** [comment]
Good find. Apparently I had some slight misconceptions in how `pass` handles sub-gpg-ids.

**Comment by metalmatze** [comment]
For me the compatibility regarding reads is important. I use [Android-Password-Store](https://github.com/zeapo/Android-Password-Store) and [browserpass](https://github.com/dannyvankooten/browserpass). Now and in the future I want to be able to at least read with these. If that gets broken I'm going to come forward and fix compatibility issues.

Writes however are a bit more tricky and I won't rely on them, as you pointed out above.

**Comment by dominikschulz** [comment]
We can definitely discuss write support for sub ids as well, but it might be a little tedious to get it right.
