### ISSUE TITLE
pager not found

### ISSUE THREAD

**Issue by pakohan** [justwatchcom/gopass#167]
after installing **gopass** on macOS I couldn't run it because of the following error.

```
$ gopass

Error: exec: "pager": executable file not found in $PATH
$
```

It's really hard to find out what this means, Google does not yield any good results since I didn't know what it's supposed to do. After reading the source I found out the binary name can be overwritten by the PAGER env variable, so I thought it's a bash builtin. This showed me that a program like `less` is meant. Then it's simple to run gopass. Nevertheless, not the best UX

**Comment by dominikschulz** [comment]
Thank you for reporting this issue. We haven't been able to reproduce this, so far, but I'll get back to you.

On the one hand this feature should be better documented, so anyone running in this issue will get some help from the docs.

On the other hand the `pager` trick only seems to work on Linux. We may want to default to something else (e.g. `/usr/bin/less`) on macOS.
