### ISSUE TITLE
Bad git config keyname for gpg key

### ISSUE THREAD

**Issue by gzugmeyer** [justwatchcom/gopass#17]
In https://github.com/justwatchcom/gopass/blob/ab10cac22e2b79e617031ff6febdd7b0d00e04ad/password/git.go#L79

```go
cmd := exec.Command("git", "config", "--local", "user.signkey", sk)
```

must be 

```go
cmd := exec.Command("git", "config", "--local", "user.signingkey", sk)
```

**Comment by gzugmeyer** [comment]
The git documentation say the same : https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#__code_user_signingkey_code

**Comment by dominikschulz** [comment]
Thank you very much for reporting. This one must have slipped through.
