### ISSUE TITLE
Don't auto pull & push when adding recipients

### ISSUE THREAD

**Issue by metalmatze** [justwatchcom/gopass#170]
When adding a recipients gopass decrypts & encrypts all files one after another. This is ok when running locally. Sadly this gets really slow if auto pull & push is enabled, because gopass does a `git pull` & `git push` after finishing every single file.
Workaround:
```bash
gopass config autopull false
gopass config autopush false
gopass recipients add (--store pluto) 1234ZXCV...
gopass config autopull true
gopass config autopush true
```
It would be awesome to disable this behavior by default if a recipients is being added.

This isn't super important, just nice to have.

**Comment by dominikschulz** [comment]
Yes, I agree. Noticed that as well. Maybe we can implement a work around for 1.3 and a proper fix when we revamp the config handling in 1.4 (or later).
