### ISSUE TITLE
Ability to generate a new password for an existing record

### ISSUE THREAD

**Issue by i1skn** [justwatchcom/gopass#172]
A use case would be if you want to change a password for an existing record, let's say `example.com`.
So now I would need to use `gopass generate example.com` and here I would lose all the information, which was stored next to the password. So following:
```
<password>
login: user@example.com
2FAcodes:
2314
4321
4213
4231
etc...
```
would be transformed to:
```
<new_password>
```

I was thinking, would it be nice to have some sort of `regenerate` functionality, which will gonna change only the first row of the record to the new password.

If there is a way to do it differently right now - please share it!

**Comment by dominikschulz** [comment]
Good idea. I think we should leverage the existing facilities and only every touch the first line of a secret during `generate`. That way we'd preverse everything below.
