### ISSUE TITLE
Add recipient to mount

### ISSUE THREAD

**Issue by entenfuss** [justwatchcom/gopass#174]
How or is it possible to add a recipient to a mount (and not only to the root password store)?

I've tried `gopass recipients add xyz@xyz.com` but this didn't work for the mount.

**Comment by metalmatze** [comment]
The `add` sub command takes a parameter `--store`.
`gopass recipients add --store mystore xyz@xyz.com` should do the trick for you :blush:

**Comment by entenfuss** [comment]
Great! Thank you very much. After I got your answer, I've found the description with the help command `gopass recipients add -h`.

Is it right that the command `gopass recipients add help` doesn't work (prints `gpg: error reading key: No public key`)? The command `gopass recipients help` is working..
