### ISSUE TITLE
gopass - add recipient - squash commits?

### ISSUE THREAD

**Issue by FrailWords** [justwatchcom/gopass#181]
If I add a recipient using gopass, I get individual commits for every secret.  Looking at the git history, its quite long and I am wondering if it makes sense to 'squash' all the commits for a single recipient that gets added? Or if not, why would that not make sense?

**Comment by dominikschulz** [comment]
Good catch. At the moment adding or removing recipients is implemented in a very simple way, i.e. we just re-use the existing facilities which - under the hood - will do all the work.

We could (easily) make this a little more complex to have a less cluttered history.

**Comment by FrailWords** [comment]
@dominikschulz this would be a good addition for sure.  Thanks for adding this to your milestone.  If i can help in some way with implementing this, i'd be happy to give it a try.

**Comment by dominikschulz** [comment]
Right now this would be either very hacky or very error prone to implement, but we're currently trying to figure out a sane way to implement this.

**Comment by FrailWords** [comment]
@dominikschulz thank you for the reply.  I'd be glad to help if anything is needed.
