### ISSUE TITLE
`gopass rm` does not ask for key pass, is it expected?

### ISSUE THREAD

**Issue by pavlo** [justwatchcom/gopass#19]
Hey guys!

`gopass rm test` removes the record without asking to supply the pass-phrase for the GPG key. Is it expected behavior?

Thanks!

**Comment by metalmatze** [comment]
Yes. We only check if the file exists and if it does we simply delete the `test.gpg` file, without decrypting it first. We don't need its content for obvious reasons.

https://github.com/justwatchcom/gopass/blob/master/password/store.go#L398
