### ISSUE TITLE
Can't access the first key/value pair within structured secrets

### ISSUE THREAD

**Issue by moritzheiber** [justwatchcom/gopass#192]
The scenario is that I want to create a secret with _just_ structured input, i.e. something like:

```yaml
some_secret: surprise
another_secret: even_more_surprises
```

Let's say we added this kind of structured secret under `secret/structured_secret`, when I run gopass to read it I get the following:

```
$ gopass secret/structured_secret some_secret

Error: key not found
```

However, accessing the second key works perfectly fine:

```
$ gopass secret/structured_secret another_secret
even_more_surprises
```

My expectation would be that I can access the structured secret's key/value no matter the position they're in within the object.

**Comment by dominikschulz** [comment]
Did you create the structured secret manually, i.e. using `gopass edit` (or some form of raw input)?

We have a very simple heuristic to distinguish between the *password* and the *body* of a *secret*.
The *first line* is the *password*,
everything else is the *body*. Only the *body* is parsed for (possible) YAML content.
The built-in YAML mechanisms should respect this. If not, this is definitely a bug.

**Comment by moritzheiber** [comment]
I see, so it's actually impossible to have "structured-only" secrets?

If that's the intentional behavior we're good and this is not a bug (albeit a little dissatisfying).

**Comment by dominikschulz** [comment]
No, it's certainly possible to have `structured-only` secrets.

The only thing that's perhaps a little confusing is the distinction between "Password" and "Body" in a Secret. Also this isn't really explained well anywhere in the docs I think.

Could you please help me understand your usecase and answer my question how you initialy created this secret?

**Comment by moritzheiber** [comment]
Oh, sorry, of course, I forgot: Yes, I used a simple
```
gopass edit secret/structured_secret
```

and then inserted the structured secret.

**Comment by dominikschulz** [comment]
Ok, thanks for elaborating.

While doing that you probably *didn't* leave the first line empty (how should you know).

We'll try to come up with a solution for this ...

**Comment by moritzheiber** [comment]
I mean, you could use the YAML spec and have people use three dash characters for "structured-only" secrets to start it off, I guess?

Thanks for your pointer though, I'm going to relay this to my colleagues in the meantime.

**Comment by dominikschulz** [comment]
Strictly speaking these [`Document Markers`](http://yaml.org/spec/1.2/spec.html#id2800401) are not required by the spec, but we should evaluate if they make sense.
Could be a good idea.
