### ISSUE TITLE
OTP Support?

### ISSUE THREAD

**Issue by oleerik** [justwatchcom/gopass#195]
Hello!

Pass supports otp through pass-otp.
Would this be possible for gopass?

**Comment by dominikschulz** [comment]
Use `gopass totp`.

https://github.com/justwatchcom/gopass/blob/master/main.go#L267

**Comment by metalmatze** [comment]
To be fair this is not yet in the latest release.
So either use the current `master` branch to build gopass yourself or wait patiently until we release the next version. :wink:

**Comment by oleerik** [comment]
Thank you and good, then I don't have to feel dumb! Seems like it's included when installing with go get.

**Comment by dominikschulz** [comment]
Oh, I'm sorry. I was under the impression that this is already released. Thanks for pointing that out @metalmatze
