### ISSUE TITLE
`gopass show path/to/yaml key` : "cannot unmarshal !!map into string"

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#196]
## Context 

From an updated install 
```
mfronton@lilbox:~$ go get -u github.com/justwatchcom/gopass
mfronton@lilbox:~$ gopass version
gopass HEAD (n/a ) go1.8.3
mfronton@lilbox:/opt/go/path/src/github.com/justwatchcom/gopass$ git describe
v1.2.0-18-gd249f00
```

From a newly created YAML password file : 
```
mfronton@lilbox:~$ gopass edit issue/yaml_support
mfronton@lilbox:~$ gopass show issue/yaml_support
---
pass: xxxxx
url: https://1.2.3.4/app
user: admin
foo:
  bar: baz
```

## What I do

I try to access any of the yaml key : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url
```
## What I get

I get an error message : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url

Error: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
```

## What I expected

The YAML is actually valid : 
```
mfronton@lilbox:~$ go get github.com/bronze1man/yaml2json
mfronton@lilbox:~$ apt-get install jq
mfronton@lilbox:~$ gopass show issue/yaml_support | yaml2json | jq '.'
{
  "pass": "xxxxx",
  "foo": {
    "bar": "baz"
  },
  "url": "http://1.2.3.4/app",
  "user": "admin"
}
```

So I expected the value of `url:` key to be displayed : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url
https://1.2.3.4/app
```

**Comment by frntn** [comment]
I forgot to mention it works well without the yaml `bar:` subkey

**Comment by dominikschulz** [comment]
We only support flat maps.

Support for nested maps or any other more complex YAML documents is not available right now.
We'd love to see PRs lifting this limitation.

**Comment by frntn** [comment]
**Noob question :** Isn't it possible to reuse the `github.com/ghodss/yaml` library already used for your `config.yml` file ? (where nested maps are used for mounts for example)

**Comment by dominikschulz** [comment]
It's not about the library. All proper YAML libraries support nested maps.

The question / challenge is how to deal with the (decoded) data in gopass, so that we get a proper UX.
Things like traversing nested data structures to resolve something like `foo/bar` to yield the proper value, etc.

It's certainly possible, but not implemented right now. Any help is appreciated.
