### ISSUE TITLE
gopass show exits with status 0 when no entry is found

### ISSUE THREAD

**Issue by atbentley** [justwatchcom/gopass#197]
Current behaviour:

``` bash
$ gopass show this_does_not_exist
Entry 'this_does_not_exist' not found. Starting search...
$ echo $?
0
```

This behaviour seems a bit strange, especially if you trying use gopass in a script in which case you end up with an error message in the secret. It would be nice if gopass exited with a non-zero exit status in this instance, or if this is not possible a flag that would enable this behaviour.

OS: OS X 10.11.6
gopass: 1.2.0_2
go: 1.8.3

**Comment by dominikschulz** [comment]
Thank you for reporting this. You're absolutely right. We'll fix that.
