### ISSUE TITLE
gopass recipients add fails

### ISSUE THREAD

**Issue by danilobuerger** [justwatchcom/gopass#20]
When I try to add a new recipient, gopass fails like so:

```
❯ gopass recipients add ##REMOVED###
gpg.listKeys: /usr/local/bin/gpg [gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys ##REMOVED###]
Do you want to add '##REMOVED###' as an recipient? [y/N]: y
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	modified:   .gpg-id

no changes added to commit

Error: failed to committ files to git: exit status 1

```

**Comment by mwolny** [comment]
@danilobuerger I have run into the same issue. As the workaround, you could try to use `gopass git` command.

**Comment by froderick** [comment]
@mwolny I'm seeing the same issue. Not clear how to use `gopass git` to work around this. If the .gpg-id includes the new recipient, `gopass recipients add` refuses to continue.

**Comment by dominikschulz** [comment]
We confirmed this bug and plan to release a fix early next week.

**Comment by mwolny** [comment]
@froderick `gopass git add .gpg-id`, `gopass git commit`, `gopass git push origin HEAD`. File `.gpg-id` contains list of gpg keys used during the encryption step.
