### ISSUE TITLE
gopass init works at second time

### ISSUE THREAD

**Issue by tclass** [justwatchcom/gopass#201]
I tried gopass init and gopass asked me about which key I want to use. I typed in 0 and gopass asked again the same question.

```➜  ~ gopass init
Please select a private key for encryption:
[0] 0xC0D713B47D60A575 - tclass <xxx@example.com>
Please enter the number of a key (0-0) [0]: 0
Please select a key for signing Git Commits
[0] 0xC0D713B47D60A575 - tclass <xxx@example.com>
Please enter the number of a key (0-0) [0]: 0
```

**Comment by dominikschulz** [comment]
I admin that the output may be a little misleading and we can probably improve this, but it's not asking the same question twice.

First it is asking for your `GPG encryption key` and after that it is asking for your `git sign key`.
We should make the difference more clear and/or just use the same key for both.
