### ISSUE TITLE
Unable to show password on OSX

### ISSUE THREAD

**Issue by vesparny** [justwatchcom/gopass#209]
Hi, thanks a lot for this amazing tool.

I am trying to use it on my mac and I get the following error while trying to show a password

```bash
$ GOPASS_DEBUG=true  gopass show ale
[DEBUG] Loaded config from /Users/aarnodo/.config/gopass/config.yml: &{AlwaysTrust:true AskForMore:false AutoImport:true AutoPull:true AutoPush:true ClipTimeout:45 Debug:false FsckFunc:<nil> ImportFunc:<nil> LoadKeys:true Mounts:map[] NoColor:false NoConfirm:false Path:/Users/aarnodo/.password-store PersistKeys:true SafeContent:false Version:}
[DEBUG] gpg.listKeys: /usr/local/bin/gpg2 [/usr/local/bin/gpg2 --with-colons --with-fingerprint --fixed-list-mode --list-public-keys noname (This is a key I only use to encrypt my passwords. Not to be shared) <noname@example.com>]
[DEBUG] gpg.Decrypt: /usr/local/bin/gpg2 [/usr/local/bin/gpg2 --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --decrypt /Users/aarnodo/.password-store/ale.gpg]

Error: Failed to decrypt

```

I do not get the gpg prompt asking for password

if I run the command 

```bash
/usr/local/bin/gpg2 --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --decrypt /Users/aarnodo/.password-store/ale.gpg
```

I do get it correctly

if I try to show the password using `pass`, after I've insert the master password in the prompt, I am able to see it.

If I now try tu use `gopass`, I am also to see the password as well. I guess because the gpg master password is cached, and gopass does not try anymore to display the prompt

<img width="809" alt="screen shot 2017-07-21 at 10 50 35" src="https://user-images.githubusercontent.com/82070/28456400-744b8034-6e02-11e7-9bf0-6d17b1116c5c.png">

**Comment by vesparny** [comment]
I guess it's a duplicate of #208

**Comment by jamesboswell** [comment]
FYI,  I think this is due to the Homebrew formula updating GPG.   The tell-tale sign for me was `gpg2 
 command not found` 

Run `brew doctor` and see if **gnupg** is listed as unlinked.   This was true for me.

```
brew link --overwrite --dry-run gnupg
Would remove:
/usr/local/bin/dirmngr -> /usr/local/Cellar/dirmngr/1.1.1_2/bin/dirmngr
/usr/local/bin/dirmngr-client -> /usr/local/Cellar/dirmngr/1.1.1_2/bin/dirmngr-client
/usr/local/share/man/man1/dirmngr-client.1 -> /usr/local/Cellar/dirmngr/1.1.1_2/share/man/man1/dirmngr-client.1

$ brew link --overwrite gnupg
Linking /usr/local/Cellar/gnupg/2.1.22... 71 symlinks created

##  Now gpg2 is properly symlinked
gpg2
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Go ahead and type your message ...
^C
gpg: signal Interrupt caught ... exiting
```

Now that **gpg2** is properly symlink,   **gopass** should be able to reach it.   My errors stopped.
