### ISSUE TITLE
Create a CLI wizard-like start experience

### ISSUE THREAD

**Issue by zwacky** [justwatchcom/gopass#22]
would be great to take the user by the hand to some extent, e.g. by showing choices à la yeoman cli:

![cli experience](https://camo.githubusercontent.com/592fdfd145978b98a1ac4b04ec22d25cf19ee6b4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3137303237302f3739343530302f34316532643439382d656361322d313165322d386466352d3936326639666139346336332e706e67)

**Comment by dominikschulz** [comment]
This was already implemented by #387 and #390
