### ISSUE TITLE
Error when fetching from source:

### ISSUE THREAD

**Issue by iamjamieadams** [justwatchcom/gopass#221]
I'm recieving an error when trying to fetch the project from the GIT repository. I'm not all that familiar with Go, so apologies if I am missing something obvious:

    adamsj@electra:~$ go get -u github.com/justwatchcom/gopass
    # github.com/justwatchcom/gopass/action
    .go/src/github.com/justwatchcom/gopass/action/totp.go:67: undefined: time.Until

**Comment by zwopir** [comment]
Hi,

thanks reporting the issue. I suspect it's a go version problem, as time.Until has been added more or less recently (see https://github.com/golang/go/issues/14595). Can you go a `go version` and post the output here?! I just tried to reproduce the issue and wasn't able to do so with go1.8.

**Comment by dominikschulz** [comment]
FYI: We always develop and test against the latest stable Go release only.
We might mention this in the docs.

**Comment by iamjamieadams** [comment]
Thanks for your help. Solved by getting rid of the older Go packages from the Ubuntu repos and installing 1.8.3 manually.
