### ISSUE TITLE
Question : How to add all recipients pubkeys in one command ? 

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#223]
Is there a command allowing one to add all recipients pubkeys (`.gpg-keys/*`) in one command ?

For example : 
```
gopass recipients importall 
```

Thanks

**Comment by dominikschulz** [comment]
In #204 we implemented a variant of this. This change makes `gopass recipients` load any missing keys.

**Comment by frntn** [comment]
Yeah thanks :smile: 
Love to see the pace of this project.

I plan to take some time to learn golang and contribute soon enough :wink:
