### ISSUE TITLE
Multiple recipients vs. git signing key

### ISSUE THREAD

**Issue by marthjod** [justwatchcom/gopass#224]
Hi, I'm playing around with the multi-recipient feature and wanted to check if I'm using it correctly or overlooking something.

I initialized a store on machine A with 2 recipients (a, b). The first key (a) also serves as the git signing key and its ID is saved to .git/config.

After copying the store to machine B, I want recipient b to be able to insert secrets as well, which fails with

```
gopass set some/new/key
gopass: Encrypting some/new/key for these recipients:
 - 0x1234 - Rcpt A <first_rcpt@example.com>
 - 0xABCD - Rcpt B <second_rcpt@example.com>

Do you want to continue? [Y/n]: Y
error: gpg failed to sign the data
fatal: failed to write commit object

gopass git config user.signingkey
first_rcpt@example.com
```

Modifying the store git config fixes this on B:

```
gopass git config user.signingkey second_rcpt@example.com

gopass set some/new/key
gopass: Encrypting some/new/key for these recipients:
 - 0x1234 - Rcpt A <first_rcpt@example.com>
 - 0xABCD - Rcpt B <second_rcpt@example.com>

Do you want to continue? [Y/n]: y
[master e4c4e50] Save secret to some/new/key: Edited with vim
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 some/new/key.gpg
```

Is there a different/preferred way to allow multiple recipients to add secrets to the same shared store maybe?

Either way, I would like the docs to elaborate more on the recipients features. I could also try to contribute some examples/pointers?

**Comment by dominikschulz** [comment]
So far we've never thought of having a shared store. Our primary use case always was to sync the stores via git. This way the per-repo config is automatically excluded.

Right now I don't see a good way to support your use case while leaving repo signing enabled and quite frankly I don't really understand why you want to work with a shared store.

If you want to contribute docs for this or other use cases that would be very well received.

If you could elaborate a little more on why you need this use case we may come up with a solution.

**Comment by marthjod** [comment]
Thanks for clearing things up.
My use case is plain-copying (i.e. without git) one store for use across different devices.
I should probably simply exclude any local git config when copying the store and be good ;)
