### ISSUE TITLE
feature suggestion: don't overwrite other fields when generating a new password

### ISSUE THREAD

**Issue by bonds** [justwatchcom/gopass#229]
I use multiline passwords, with the password on the first line and other fields like login and url on subsequent lines, for use with browserpass, passff, and other web browser integrations. When its time to rotate my password for some account, I like to use ````gopass generate example.com 32```` and overwrite my old example.com password. BUT, that also overwrites the other lines/fields in the password file. I suggest only overwriting the first line, the password line, leaving the rest unchanged.

**Comment by metalmatze** [comment]
As I was looking into the source I saw that this already has been fixed. 
https://github.com/justwatchcom/gopass/pull/177
I can confirm that it still works.

Is your gopass version up-to-date?

**Comment by bonds** [comment]
No, I was not up to date, I was on aaa7aa6e819080cdb739d5c63389f339779b25f8. ````go get -u github.com/justwatchcom/gopass```` got me onto the latest and I can confirm it works. Sorry for the noise!
