### ISSUE TITLE
Entries aren't accessible if they start with the name of a mount

### ISSUE THREAD

**Issue by ioben** [justwatchcom/gopass#231]
A mount name that is a prefix of any entries breaks those entries, even if the prefix isn't a full directory name.  I would expect the mount to only take precedent if it's an entire directory name (aka ends in a `/`).

Reproduce:

```
gopass edit TESTfolder/some-entry
gopass init --alias TEST --store ~/.password-store-TEST
gopass show TESTfolder/some-entry
> Entry 'TESTfolder/some-entry' not found. Starting search...
> TESTfolder/some-entry
gopass mounts rm TEST
gopass show TESTfolder/some-entry # Works
``` 

Version: gopass 1.2.0 (e54f54bac4b47fd46b7e35c98ee4c66eeb7abbaf ) go1.8

**Comment by dominikschulz** [comment]
Indeed, this is a violation of the mount design goals. We'll investigate.
