### ISSUE TITLE
Feature proposal : machine-readable (raw) format for scripting purpose 

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#253]
# Context

Today ouput is human-readable only : 
```
$ gopass perso
perso (/home/frntn/.password-store/perso)
└── some
    ├── more
    │   └── example
    ├── secret
    │   ├── or
    │   │   └── here
    │   ├── there
    │   │   ├── again
    │   │   ├── too
    │   │   └── too2
    │   └── here
    └── stuff
```

# Feature Proposal

Add a `-raw` to make it machine-readable ( inspired [from aptly](https://www.aptly.info/doc/aptly/mirror/list/) )

```
$ gopass -raw perso
perso/some/secret/here
perso/some/secret/there/again
perso/some/secret/there/too2
perso/some/secret/there/too
perso/some/secret/or/here
perso/some/more/example
perso/some/stuff
```

**This is a must have for scripting purpose** and so for massive gopass adoption :wink:

**Comment by dominikschulz** [comment]
Did you try `gopass list --flat`?

**Comment by frntn** [comment]
Hmmm...
I had never used the `list/ls` commands (as it's the default)
So I couldn't find the available options (`gopass list -h`) 

Thanks !
