### ISSUE TITLE
Do not default to symbols in generated passwords

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#264]
The new [NIST guidelines](https://github.com/usnistgov/800-63-3) no longer recommend special characters in passwords and I always run `gopass generate -n`, so I think we might as well change the default to *not include symbols*.

**Comment by metalmatze** [comment]
Personally I've always used `generate -n`.
Should we add some kind of deprecation warning question for the people that rely on `generate` to use symbols up until now. Maybe until we release 1.4?
It's a breaking change after all.

**Comment by dominikschulz** [comment]
Yes, it's small breaking change. Though about supporting both flags, but that was IMHO too much extra code.

How should this warning look like?
Do you think we should keep supporting `-n`?

**Comment by vyachkonovalov** [comment]
How can I generate a password with symbols in gopass 1.10.1?

**Comment by dominikschulz** [comment]
`gopass generate -h` should show you the available options.
