### ISSUE TITLE
Specify character set for generated passwords

### ISSUE THREAD

**Issue by alexmironof** [justwatchcom/gopass#269]
Hi! Thanks for your awesome work! :+1: 

I've tried to set `PASSWORD_STORE_CHARACTER_SET` env variable for restricting character set wich I need to use when generating passwords for web development(passwords without quotes and some special chars), but has no luck.

Is there a way to restrict character set used for generated passwords?

**Comment by dominikschulz** [comment]
There are the `-s` (new) and `-n` (deprecated) options to `gopass generate`. Does that help?
Otherwise I'd check how clean this change could be implemented.

**Comment by alexmironof** [comment]
@dominikschulz Thanks for the response! In some cases generating passwords made of only letters and numbers helps.
But not for generating short but strong passwords. In some cases I need very strong password with length=6 like for database user, wich I then send to somebody and add inside a config file surrounded by quotes like in wordpress configs.
And if I have double or single qoutes in generated 
password, my php variable inside config will fail with error.

**Comment by alexmironof** [comment]
maybe there is an elegant way to override `const syms = ...` inside pwgen file from enviroment variable or from flag parameter?

**Comment by dominikschulz** [comment]
Yes, we could do that. But please keep in mind that there is no such thing as a _short but strong password_. See also: [relevant XKCD](https://xkcd.com/936/)

**Comment by alexmironof** [comment]
Thanks!

Wow nice comics :rofl:.
From now I'll always use default password length :+1: if I could customize the character set :smile:
cause there a big chance to have many qoutes in 24 symbols length password

**Comment by alexmironof** [comment]
Thanks! I'll check it out today

**Comment by alexmironof** [comment]
@dominikschulz How I can cooperate `GOPASS_CHARACTER_SET` env variable with deprecated `-n` flag?
I mean by default I need passwords without some special chars, but sometimes I need just alphanumeric passwords and if env variable is setted up I can't use `-s` or `-n` flag - it just dont work

**Comment by dominikschulz** [comment]
`GOPASS_CHARACTER_SET` will override any command line flag. Just set `GOPASS_CHARACTER_SET` to include the characters you want.

We will change the default behaviour to not include special characters soon, as they provide little additional security (over just using longer passwords).
