### ISSUE TITLE
gopass autocompletion broken on macOS

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#273]
Running `source <(gopass completion bash)` leaves no traces in `complete -p` and no autocompletion works.

**Comment by gburtini** [comment]
Do you have a workaround?

**Comment by martinhoefling** [comment]
https://stackoverflow.com/questions/32596123/why-source-command-doesnt-work-with-process-substitution-in-bash-3-2

My OSX has bash 3.2 installed so this won't work with process substition.

**Comment by dominikschulz** [comment]
Thanks for the explanation, will try the workaround.

**Comment by gburtini** [comment]
I can confirm this works on GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17).

`source /dev/stdin <<<"$(gopass completion bash)"`
