### ISSUE TITLE
gopass edit fails if $EDITOR is not set

### ISSUE THREAD

**Issue by jimb0bmij** [justwatchcom/gopass#279]
jimb0@local ~]$ gopass edit Foo/Bar/foobar/console/info

You need a passphrase to unlock the secret key for
user: "Jim"
4096-bit RSA key, ID 9999999, created 2017-08-21 (main key ID 9999999)

Error: failed to run editor with /dev/shm/gopass-edit943276169/tempfile file

gopass 1.3.1 (8284376) go1.8 linux amd64
CentOS Linux release 7.3.1611 (Core)

I think this might related to the other issue I submitted. But if I do the above with "pass" instead of "gopass" works just fine.

**Comment by jimb0bmij** [comment]
I think I figured it out. Not sure why it has this issue. But I did "export EDITOR='vim'" then did "gopass edit Foo/Bar/foobar//console/info"

Then it worked no issues.

**Comment by dominikschulz** [comment]
Thanks for reporting this. I notice this before without filing an issue.
If `$EDITOR` is not set gopass fails to launch any. Maybe we should consider trying an default editor (which?).
