### ISSUE TITLE
Add user to --store How to re-encrypt

### ISSUE THREAD

**Issue by jimb0bmij** [justwatchcom/gopass#287]
So I have a store with data in it work fine. I add a new user via gopass recipients add bar --store Foo

The user bar can not see any data Failed to decrypt until, I do a gopass edit on a "record".

How do we get it to go though the whole store and add the new user gpg key?

Thanks

**Comment by metalmatze** [comment]
I think you're messing up the order of arguments:
```diff
- gopass recipients add bar --store Foo
+ gopass recipients add --store Foo bar
```
That hopefully does the trick. It's not very intuitive to say the least, but sadly that's how it's handled by the cli library we use as a basis for gopass.

**Comment by jimb0bmij** [comment]
Thanks for the answer. But both ways gets me the same answer. Which I guess is good.

Error: Recipient already in store

After I add a user. How do I get it to re-encrypt the WHOLE store?? With the new added user?

Thanks!

**Comment by dominikschulz** [comment]
You can always remove a certain user and add it again, which should trigger a full re-encrypt.

```
gopass recipients --store Foo remove bar
gopass recipients --store Foo add bar
```

**Comment by jimb0bmij** [comment]
You are correct I removed user then added it looked like it re-encrypted all the files.

But command is:

gopass recipients rm bar --Store Foo 
gopass recipients add bar --Store Foo

Thanks!!
