### ISSUE TITLE
gopass does not respect sub-folder specific .gpg-id files

### ISSUE THREAD

**Issue by denefoster** [justwatchcom/gopass#288]
If you've got a sub-folder, with a different gpg-id list than the parent, gopass will in some cases "fix" it for you, and re-encrypt to a bigger audience than expected

dene@taylor-swift ~𝛀 cat .password-store/dane/.gpg-id
0CAF09E5FB3B729F
DA7B58A4759D252C

With pass:

dene@taylor-swift ~𝛀 pass insert dane/test                                                                                                            14:39:43
Enter password for dane/test:
Retype password for dane/test:
[master 1a9da8b] Add given password for dane/test to store.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 dane/test.gpg
dene@taylor-swift ~𝛀 gpg -d .password-store/dane/test.gpg

You need a passphrase to unlock the secret key for
user: "Dane Foster <dane@nzrs.net.nz>"
4096-bit RSA key, ID A94923CF, created 2016-09-19 (main key ID FB3B729F)

gpg: encrypted with 4096-bit RSA key, ID 0EF69776, created 2016-09-29
      "Dane Foster (Yubikey) <dane@nzrs.net.nz>"
gpg: encrypted with 4096-bit RSA key, ID A94923CF, created 2016-09-19
      "Dane Foster <dane@nzrs.net.nz>"
test

With gopass:

dene@taylor-swift ~𝛀 gopass insert dane/test
An entry already exists for dane/test. Overwrite it? [y/N]: y
Enter password for dane/test:
Retype password for dane/test:
gopass: Encrypting dane/test for these recipients:
 - 0xXXXXXXE5FB3B729F - Dane Foster <dane@nzrs.net.nz>
 - 0xXXXXXXC3A3628080 - XXX
 - 0xXXXXXXBF6618875 - XXX
 - 0xXXXXXX7178B1A25 - XXX
 - 0xXXXXXXEC446F8AB - XXX
 - 0xXXXXXX77B545028 - XXX
 - 0xXXXXXX4759D252C - XXX

Do you want to continue? [Y/n]:

Makes it quite unusable, and not at all compatible with pass

**Comment by dominikschulz** [comment]
We clearly state in the readme that pass compatibility was an important milestone in the development of gopass but not a promise for eternity.

That being said: if someone is willing to implement this, that would be very welcome.
