### ISSUE TITLE
Skip  [y/N] prompt?

### ISSUE THREAD

**Issue by jimb0bmij** [justwatchcom/gopass#289]
Is it possible when doing "gopass recipients add 99999 --store Foo" to skip the prompt for [y/N]. Like "gopass recipients add 99999 --store Foo --yes"? 

Goal is to allow scripting of adding many users at once.

**Comment by dominikschulz** [comment]
When running non-interactively we should not prompt for input, but adding an explicit `--yes` flag is a good idea as well.
