### ISSUE TITLE
`gopass edit` should create an in-memory temporary directory on macOS

### ISSUE THREAD

**Issue by isaacazuelos** [justwatchcom/gopass#29]
MacOS doesn't have a `/dev/shm` directory so `gopass` falls back to `ioutil.TempDir` which will write plaintext to the disk. `pass` does a lot of work on [darwin] to avoid this.

[darwin]: https://git.zx2c4.com/password-store/tree/src/platform/darwin.sh#n18

**Comment by dominikschulz** [comment]
Good one. Since my primary platform is linux I didn't notice that so far. We'll look into that.

**Comment by jkseppan** [comment]
I had the same problem, and got the script to work with #69.
