### ISSUE TITLE
Missing in-place option for generate

### ISSUE THREAD

**Issue by kepi** [justwatchcom/gopass#295]
I don't see any option how to update existing passwords, which seams really inconvenient.

In `pass` there is option `-i` or `--in-place` for `generate` which allows replacing only first line. In `gopass generate` help there is help text:

> Optionally replace only the first line of an existing file with a new password.

But there is no info how to do that.

Btw. this is one of things I found extremely inconvenient even in original `pass`. I think `gopass` can go one step further and if there is existing entry, it can simply ask user if he wants overwrite whole entry or only update password. IMHO it would be best to change default behavior to `inplace` without asking but we probably don't want to behave differently then `pass`?

**Comment by dominikschulz** [comment]
Gopass generate will only modify the first line, i.e. it already matches your suggested behavior. We need to explain this in the docs.

**Comment by kepi** [comment]
thanks, amazing :) It probably didn't work in previous version (I tried today in 1.2.0 and it overwritten whole entry) and after upgrade I checked only doc and not behavior.

Should this remain open until doc is fixed?

**Comment by dominikschulz** [comment]
Yes, please keep it open. This must be documented in the Readme and the help output.
