### ISSUE TITLE
"search" support

### ISSUE THREAD

**Issue by soulware** [justwatchcom/gopass#3]
`pass search` works the same as the documented `pass find` (at least I think that's what it does...)
Any chance you could support `search` as an alias to `find`?

**Comment by soulware** [comment]
Right now gopass gives a confusing error message -

```
gopass search foo

Error: Entry is not in the password store
```

Because `search` is not in the password store (not `foo`).

**Comment by metalmatze** [comment]
There is no `gopass search` command right now. Seems like we missed that one, but it's pretty easy to add it as an alias for `gopass find`. Thanks for reporting!
