### ISSUE TITLE
gopass insert should only overwrite the password in a secret, not everything

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#301]
Running `gopass insert foo/bar` on an existing entry `foo/bar` will overwrite the whole entry (i.e. password and any data thereafter) while `gopass generate foo/bar` on the same entry will only touch the first line.

This is inconsistent and counter-intutive. We should match the behaviour of both commands.

**Comment by sgeisbacher** [comment]
is already someone on it, i would like to fix it
