### ISSUE TITLE
Unhelpful error message when subcommand does not exist

### ISSUE THREAD

**Issue by adius** [justwatchcom/gopass#307]
I thought there was a `create` subcommand, although it's really called `insert` (how about setting `create` as an alias?). The error message however didn't help. I thought it means that something with my template file is wrong or similar.

```sh
gopass create google.com

Error: no YAML document marker found
```

**Comment by dominikschulz** [comment]
Good suggestion, thank you.
Should be easy to fix.

**Comment by dominikschulz** [comment]
FYI: I've decided not to add an `create` alias to `insert` right now, because I think we might want to add a separte `create` command as part of #282 . If not we can still add the alias on `insert`.

**Comment by adius** [comment]
I like the idea you're proposing in #282 😊
