### ISSUE TITLE
Feature proposal: only print newline when output goes to a terminal

### ISSUE THREAD

**Issue by erikdoe** [justwatchcom/gopass#324]
When gopass shows a secret it appends a newline character. This makes sense when gopass is invoked from a terminal and a human consumes the output. However, when the output is sent to another command, the newline character usually has to be stripped off using `tr` or similar. Doable, but a bit annoying.

The proposal is to detect where the output is sent to and only append the newline character if the output goes to a terminal.

I believe the change needs to be made in `show.go` at the end of the `show` function: https://github.com/justwatchcom/gopass/blob/2d46fce7a0b8227f7f986f38b6a4fd2a3e2c41f6/action/show.go#L96

There is a Go package to determine whether the output is going to a terminal or not: https://godoc.org/github.com/mattn/go-isatty

Sorry, I would do a PR but I have zero experience with Go and its tooling.

**Comment by dominikschulz** [comment]
That is a good thing idea and very easy to, since we already detect if output is going to a terminal or not.

**Comment by dominikschulz** [comment]
Do this look ok?
 https://github.com/dominikschulz/gopass/commit/bd54ed26b3be6610f490b235ec0db03ee9846bbd
