### ISSUE TITLE
"In-place updates to existing passwords" section in documentation is out of date

### ISSUE THREAD

**Issue by bddenhartog** [justwatchcom/gopass#332]
> ### In-place updates to existing passwords
> 
> Running gopass generate foo/bar on an existing entry foo/bar will only update the first line of the secret leaving and trailing data in place.
> 
> **WARNING: At the moment this differs from the behaviour of gopass insert which will overwrite the whole entry. We plan to fix this.**

The emboldened statement is invalid as of #301.

**Comment by dominikschulz** [comment]
Thank you very much. We missed that when merging #301 :+1:
