### ISSUE TITLE
gopass uses wrong store location on windows

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#342]
From https://github.com/justwatchcom/gopass/issues/334#issuecomment-330208103:
> Issue 1:
> By default, gopass should initialize the password store to a directory called ".password-store" in the home > directory. However, on Windows, it initializes it to "C:.password-store". So, whatever code you added to the "location.go" file needs to be also added to the other part of the code.

**Comment by SmaugTheGreat** [comment]
Seems to work for me on Windows 10

**Comment by dominikschulz** [comment]
Verified to be fixed in Windows 7 as well.
