### ISSUE TITLE
Content should not be tampered with

### ISSUE THREAD

**Issue by frntn** [justwatchcom/gopass#344]
# What I do

Checking file hash before/after being inserted to gopass

# What I expect

I expect the file to be the same.
So the hash are equals

# What I have

The hash are actually differents
```
$ gopass bintest < before.txt
$ gopass bintest > after.txt
$ md5sum before.txt after.txt
db81a851af569aef93d40c18fb78da3f  before.txt
3b96771673ab6a08085bd21f3609a36b  after.txt
```

# My understanding

Changing stored content are not the behavior one would expect from a vault :confused: 

I understand gopass helps securely share text files accross multiple platforms and may require text files translation (like we have for ftp file transfert modes).
Sharing binary files requires using specific `gopass binary`

# My analysis
 
I have digged into this default text-mode behavior and realized the OS-specific line ending characters are not translated (which is what is being expected here as for ftp once again...)
The behavior seems to just to add a `\n` character at the very end of every files.

Following bash script test most `binary/text` X `cr/lf` combinations : https://gist.github.com/frntn/ae015b997a8255e3c99b3989d8b89af7

**Comment by frntn** [comment]
Hmmmm... I tried to play with the `binary` subcommand and have to admit I am very confused.

I first insert a binary file, using the binary mode.
```
$ echo -n $'\x01\x63\x61\x74' > before.bin
$ gopass binary cat perso/bintest/cr.bin < before_cr.bin
```

When I try to retrieve its content I get the base64 encoded version of the original content : 
```
$ gopass perso/bintest/cr.bin
AWMNYQ10DQ==
$ gopass perso/bintest/cr.bin | base64 -d | od -c
0000000 001   c  \r   a  \r   t  \r
0000007
```

Actually reading/copying/moving actions to binary files require the use of `binary` subcommand : 
```
$ gopass binary cat perso/bintest/cr.bin | od -c
0000000 001   c  \r   a  \r   t  \r  \n
0000010
```

Deleting seems to have a bug : 
```
$ gopass perso/bintest
perso/bintest
└── cr.bin (binary)
$ gopass rm perso/bintest/cr.bin
Error: Entry is not in the password store

I have found the following workaround 
```
$ gopass rm perso/bintest/cr.bin.b64
```

Which I understand shows some reserved filename extensions with some weird side effects : 
```
$ echo "ascii content" | gopass insert perso/bintest/readme.txt
$ gopass perso/bintest
perso/bintest
└── readme.txt
$ echo "ascii content" | gopass insert perso/bintest/readme.txt.b64
$ gopass perso/bintest
Failed to add file perso/bintest/readme.txt to tree: File readme.txt exists
perso/bintest
└── readme.txt (binary)
```

**Comment by dominikschulz** [comment]
Thank you very much for your analysis! The bash script is very helpful :100: 

There seems to be at least one bug and several usability issues. I'll try to split these so we can track them one by one.

**Comment by dominikschulz** [comment]
Right now we expect any content inserted into a secret to be unaltered when retrieving it.
This includes anything, even line breaks.
We should implement proper unit/integration tests to ensure this status quo.

There is but one exception we should consider: If the secret does not contain a final newline IMHO we should add this final newline when printing to stdout!

Any discussion if and how we should handle text files (line breaks) across different platforms should be kept in #348, please.

**Comment by frntn** [comment]
If _when printing to stdout_ means _when attached to a TTY_
If I redirect stdout to file or a pipe the final newline should not be inserted.

Do you agree ?

**Comment by dominikschulz** [comment]
Yes, exactly.

I propose we check if the secret has a trailing newline already. If it has OR if output is being redirected somewhere (pipe, file, ...) we do nothing.
If output if going to a terminal AND there is no trailing newline we should append a final newline to avoid messing up the terminal.
