### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#346]
From https://github.com/justwatchcom/gopass/issues/334#issuecomment-330316084:

> From the README.md file:
> 
> Choose one of:
> 
> $ gopass init gopher@golang.org
> $ gopass init A3683834
> $ gopass init 1E52C1335AC1F4F4FE02F62AB5B44266A3683834    # preferred
> You don't really define what these 3 choices are or the implications of initializing a password store with > either choice. (It's just telling gopass which GPG key to use, right?)
> 
> Can't all this just be removed? README.md should probably advise the user to just do the simple gopass init, since the built-in wizard guides the user through choosing a GPG key from all of the ones found. Users probably won't typically have to specify which GPG key to use inline, unless they are writing a > script to create a gopass store for some reason.

The README has grown pretty large. We should consider moving the more advanced parts to separate docs.

**Comment by Zamiell** [comment]
@dominikschulz You closed this issue, but didn't actually address the problems outlined in my quote.

Explicitly,

* You don't define what these 3 choices are or the implications of initializing a password store with either choice. Annotate this, perhaps inline with a `# comment`.
* Prior to the 3 examples, you should add a line put `gopass init # Recommended; the wizard will guide you through choosing a GPG key`

**Comment by Zamiell** [comment]
Furthermore,

```
If you already have a password-store that you would clone to the system you can take one short cut:
```

Should probably have a comma after the word "system".

**Comment by dominikschulz** [comment]
Thank you very much for making us aware of possible improvements.
We're quite busy right now, feel free to open an PR.

**Comment by Zamiell** [comment]
I will open a PR.
1) Just so I'm clear, the three different things are just 3 ways of specifying the GPG key, right?
2) "A3683834" can be gotten by doing a `gpg --list-keys` and looking for the "pub" line, right?
3) What command do I run to get "1E52C1335AC1F4F4FE02F62AB5B44266A3683834"? Is it just `gpg --fingerprint`?

**Comment by dominikschulz** [comment]
From the top of my head, these three assumptions should be correct.
