### ISSUE TITLE
`gopass recipients add` with no arguments should give the user a wizard in the exact same way that `gopass init` does

### ISSUE THREAD

**Issue by Zamiell** [justwatchcom/gopass#351]
`gopass recipients add` without any additional parameters will just fail.

It should instead show a wizard. Specifically meaning that it should shows the user a list of all of the currently installed PGP public keys on the system and lists them by number along with the name/email attached to them so that the user can easily just pick one from the list (which is what happens when you do a `gopass init`).

Finally, `gopass recipients remove` should also have the same functionality.

**Comment by dominikschulz** [comment]
We should definitely implement this for `gopass recipients remove`.
I'm not so sure about `gopass recipients add`. This could produce a huge output that would be very hard to navigate (e.g. I've got around 2k public keys in one keyring).

We may implement this is there are less than a certain number of keys available.
