### ISSUE TITLE
When searching after not finding an exact match, the -c parameter is ignored

### ISSUE THREAD

**Issue by thebigjc** [justwatchcom/gopass#377]
Consider:

`gopass show -c foo`

If `foo` isn't found, we act as if `find` was passed instead of `show`, which is very helpful.

However, the `-c` parameter is ignored, and a quick tap on 'enter' for a result without reading the help text at the bottom of the screen results in the secret going to standard out, when the initial command wanted the value to the clip board.
Options:
1. Pass the `-c` flag to the `find` action, and preserve it
2. Allow `find` to take `-c` as a parameter as well

In both cases, the `find` behaviour would change from checking which key was pressed and always copy to the clipboard.

Happy to implement either patch as a PR, but I prefer 2.

What do y'all think?

**Comment by dominikschulz** [comment]
Fixed by #378
