### ISSUE TITLE
does not work when gpg-agent is enabled

### ISSUE THREAD

**Issue by FlorinAndrei** [justwatchcom/gopass#39]
New to gopass, just test driving it.
- macOS 10.12.3
- gopass 1.0.0 installed from binary tarball
- gpg 1.4.20 installed from brew
- gpg-agent 2.0.30 installed from brew
- git 2.9.2

I've configured gpg-agent to start automatically in `~/.bash_profile`:

```
[ -f ~/.gpg-agent-info ] && source ~/.gpg-agent-info
if [ -S "${GPG_AGENT_INFO%%:*}" ]; then
  export GPG_AGENT_INFO
else
  eval $( gpg-agent --daemon --write-env-file ~/.gpg-agent-info )
fi
```

```
$ cat ~/.gnupg/gpg-agent.conf 
use-standard-socket
default-cache-ttl 28800
max-cache-ttl 86400
```

Tested the agent, and it works. If I do `gpg -d path/to/some/encrypted/file` repeatedly, I only need to enter the GPG pass once.

I've installed gopass and done `gopass init`:

```
$ gopass init
Please select a private Key for encryption:
[0] 0xXXXXXXXXXXXXXXXX - Florin Andrei <florin@XXXXXXXXXXXXXXXX>
Please enter the number of a key (0-0) [0]: 
Password store initialized for: 0xXXXXXXXXXXXXXXXX - Florin Andrei <florin@XXXXXXXXXXXXXXX>

Please select a key for signing Git Commits
[0] 0xXXXXXXXXXXXXXXXX - Florin Andrei <florin@XXXXXXXXXXXXX>
Please enter the number of a key (0-0) [0]: 
Initialized empty Git repository in /Users/XXXXXXXXXXXXX/.password-store/.git/
[master (root-commit) e0dcdef] Add current contents of password store.
 2 files changed, 53 insertions(+)
 create mode 100644 .gpg-id
 create mode 100644 .gpg-keys/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[master d984775] Configure git repository for gpg file diff.
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes
Git initialized
```

Then I've tried to insert some fake password, for testing:

```
$ gopass insert web/google.com
Enter password for web/google.com: 
Failed to restore terminal: errno 0
Retype password for web/google.com: 
Failed to restore terminal: errno 0
gopass: Encrypting web/google.com for these recipients:
 - 0xXXXXXXXXXXXXXXXX - Florin Andrei <florin@XXXXXXXXXXXXXXXXXX>

Do you want to continue? [Y/n]: 
gpg: XXXXXXXX: There is no assurance this key belongs to the named user

pub  4096R/XXXXXXXX 2016-07-25 Florin Andrei <florin@XXXXXXXXXXXXXX>
 Primary key fingerprint: XXXX XXXX XXXX XXXX XXXX  XXXX XXXX XXXX XXXX XXXX
      Subkey fingerprint: XXXX XXXX XXXX XXXX XXXX  XXXX XXXX XXXX XXXX XXXX

It is NOT certain that the key belongs to the person named
in the user ID.  If you *really* know what you are doing,
you may answer the next question with yes.

Use this key anyway? (y/N) y
                            
You need a passphrase to unlock the secret key for
user: "Florin Andrei <florin@XXXXXXXXXXXXXXXXX>"
4096-bit RSA key, ID XXXXXXXX, created 2016-07-25

gpg: problem with the agent - disabling agent use
error: gpg failed to sign the data
fatal: failed to write commit object

Error: failed to committ files to git: exit status 128
```

If I kill gpg-agent, and unset the GPG_AGENT_INFO variable (so basically disabling the GPG agent completely), then gopass works just fine, but of course it keeps nagging me about the GPG passphrase every time.

**Comment by dominikschulz** [comment]
Thanks for testing `gopass`. GPG and the subtle differences between the different platform/packages are the hardest part of this project. We didn't experience this issue during release testing but we'll look into it.

**Comment by FlorinAndrei** [comment]
Not sure if it helps or is even related, but my shell is `/usr/local/bin/bash` version 4.3.46 installed from brew.

**Comment by dragon788** [comment]
@FlorinAndrei First I'd recommend upgrading to the latest GnuPG 2.1 from brew, it is backwards compatible and brings a lot of nice features. Second do you have your key marked as trusted on your machine? `gpg --edit-key YOURKEYID` then (where `gpg>` is the prompt) `gpg> trust` then `gpg> save` . This should prevent the warnings you were getting, if you are still having trouble let us know.

**Comment by falschparker82** [comment]
In the meantime, brew has completely changed how they are dealing with these packages (they had a complete mess before with separate `gpg`, `gpg2` and `gpg21` packages) and are now finally based on the GPG 2.1 and forward branch.

TBH it wasn't completely their fault, as GPG introduced some mutually incompatible and hard breaking changes between those three versions.

Nevertheless, this should be resolved by now if you
- go with GPG 2.1+
- don't have any dependencies on GPG <2.1

Also see: https://github.com/Homebrew/homebrew-core/issues/12025

**Comment by dominikschulz** [comment]
Closing this as we think it's resolved. Please report back if you think it isn't.
