### ISSUE TITLE
Better search behavior 

### ISSUE THREAD

**Issue by adius** [justwatchcom/gopass#397]
I think the new prompt to select a secret is really cool, but I don't like that there seems to be no flag to disable it and that it is used for all search keywords.

I would expect, that `gopass <keyword>` has the current behavior, but that `gopass search <keyword>` simply displays the list to stdout.

**Comment by dominikschulz** [comment]
No sure if I undstand you correctly.

Do you simply suggest the selection wizard to be disabled when using `gopass search`?

**Comment by adius** [comment]
Yeah basically.

**Comment by dominikschulz** [comment]
Ok, thanks. We'll consider doing that.
