### ISSUE TITLE
YAML support broken

### ISSUE THREAD

**Issue by laedanrex** [justwatchcom/gopass#398]
Some of my secret are YAML documents :
```
---
key1: value1
key2: value2 
```
I've upgrade my gopass version from 1.3.2 to 1.4.1 and the access to a value inside a YAML file gives me an error : 
`gopass path/to/my/secret key1` 
1.3.2 returned : `value1` 
1.4.1 returned : `Error: failed to retrieve key 'key1' from 'path/to/my/secret': no YAML document marker found` 

I've tried to change my secret into a YAML file but nothing changed
`gopass mv path/to/my/secret path/to/my/secret.yaml`

Still got the error

Has the YAML support changed ?

**Comment by dominikschulz** [comment]
Yes, indeed. There has been a breaking change wrt. document separators.
We'll try to reproduce and consider if we better support this case.

**Comment by dominikschulz** [comment]
The problem is that the first line of the secret is empty. Some time ago we started to require YAML document markers in the *body* of the secret (i.e. not on the first line).

I've just pushed a workaround that should fix your issue.
