### ISSUE TITLE
Add support to disable colorful output

### ISSUE THREAD

**Issue by metalmatze** [justwatchcom/gopass#4]
https://news.ycombinator.com/item?id=13552756

> I'm pretty excited about this actually. Thank-you so much for your efforts. I've been using pass for awhile now, and I really love what it does, but it's a case where it feels 90% finished.
I have one desperate request; colour output as an option. Every time there is an update to pass (or I need to reinstall) I need to edit the file and change the options from " tree -C " to " tree -n "  
This is a pain in the ass. I am visually impaired. The 'default' dark-blue that tree uses for directories is unreadable to me.
My two choices for dealing with this are to use DIRCOLORS or edit the pass executable. I'd prefer to not muck about with my environment settings. (as I do not normally see any colour output)
Anyway; awesome project!

This should be doable in the future with not that much refactoring.

**Comment by dominikschulz** [comment]
We support doing `export GOPASS_NOCOLOR=true` to disable colors. Is that sufficient?

**Comment by VA3FXP** [comment]
Yes, that will work.

**Comment by dominikschulz** [comment]
Cool. Feel free to reopen if this isn't working as expected.

**Comment by Miserlou** [comment]
I suggest that this feature isn't complete until it's a) available as part of the [standard config](https://github.com/justwatchcom/gopass#edit-the-config) b) documented. Currently it's neither.

**Comment by dominikschulz** [comment]
Fixed by #33
