### ISSUE TITLE
Do not print newly generated passwords by default

### ISSUE THREAD

**Issue by bumi** [justwatchcom/gopass#410]
Currently `gopass generate` prints the newly created password by default. 
As this is sensitive data I think it should not be printed by default. We could add a flag (similar `--clip`) to additionally print the generate password. 

The `--force` for `generate` (overwrite existing password) differs from `show` (display password). Maybe it would make sense to unify these?

**Comment by dominikschulz** [comment]
Actually I'd keep the default (to be discussed, but my preference), but add a flag to copy it to the clipboard.

**Comment by bumi** [comment]
The flag to copy it to the clipboard is already there, that works fine. 

In my flow I dislike that coming back to the terminal after a few hours the password is still displayed and might get exposed.

**Comment by bumi** [comment]
awesome! 
though actually I also would not default to copying the password to the clipboard on creation :) 
but yeah it totally solves that the password gets accidentally exposed. 

thanks for all the work! gopass is such a great and helpful piece of software!
