### ISSUE TITLE
Error while re-encrypting store when adding new recipient (Osx)

### ISSUE THREAD

**Issue by funkeyfreak** [justwatchcom/gopass#412]
This is very similar to issue #304, but on OSX. I have created the default store using 
```gopass init <gpg-id>``` which created the default pass store ```~/.password-store/*``` just fine. However, when I am attempting to add a user to a store which I have just created on another machine (via ```gopass clone git@itsawonderfullife.org angelswings```), I run into several dicy errors. I run ```gopass recipients add --store=angleswings <gpg-id>``` and am greeted with the following:
```shell
Macbook-Pro:~ <user-redacted>$ gopass recipients add --store=angleswings <gpg-id>
Do you want to add '0x<gpg-redacted> - George Bailey <george@bedfordsucks.com>' as an recipient? [y/N]: y
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
Failed to get current value for <path-redacted>: Failed to decrypt
```

What makes this even more strange, is that even though this failed, if I attempt to remove the key via ```gopass recipients remove --store=angelswings <gpg-id>```, I get the following:
```shell
Macbook-Pro:~ <user-redacted>$ gopass recipients remove <gpg-id>
[DEBUG] Loaded config: &{Root:0xc42007b440 Mounts:map[angleswings:0xc42007b620] Version:1.5.0-git+HEAD XXX:map[]}
[DEBUG] Loaded config from /Users/georgebailey/.config/gopass/config.yml: &{Root:0xc42007b440 Mounts:map[angleswings:0xc42007b620] Version:1.5.0-git+HEAD XXX:map[]}
[DEBUG] [DEBUG] gpg.listKeys: /usr/local/bin/gpg [/usr/local/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys george@bedfordsucks.com]

Do you want to remove yourself (george@bedfordsucks.com) from the recipients? [y/N]: y
[DEBUG] [DEBUG] gpg.listKeys: /usr/local/bin/gpg [/usr/local/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys george@bedfordsucks.com]

[DEBUG] Stacktrace: recipient not in store
github.com/justwatchcom/gopass/store/sub.(*Store).RemoveRecipient
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/store/sub/recipients.go:96
github.com/justwatchcom/gopass/store/root.(*Store).RemoveRecipient
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/store/root/recipients.go:31
github.com/justwatchcom/gopass/action.(*Action).RecipientsRemove
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/action/recipients.go:158
main.main.func61
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/main.go:835
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.HandleAction
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:485
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.Command.Run
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/command.go:193
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.(*App).RunAsSubcommand
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:374
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.Command.startApp
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/command.go:280
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.Command.Run
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/command.go:79
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.(*App).Run
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:250
main.main
	/Users/georgebailey/go/src/github.com/justwatchcom/gopass/main.go:1011
runtime.main
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/proc.go:185
runtime.goexit
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/asm_amd64.s:2337

Error: failed to remove recipient 'george@bedfordsucks.com: recipient not in store
```

In any case, let me know if you need more details, and keep up the fantastic work!

**Comment by dominikschulz** [comment]
- Actually the recipient handling could be a little more robust, right now we add the recipient before reencrypting. Technically this is a straight forward solution, but UX is not great if things go wrong
- I can't see why removing the recipient fails. It should have been added to the store in the first place, so removing it should succeed as well. Did you forget the `--store` argument on the `gopass recipients remove <gpg-id>` call? Maybe you could do a `cat ~/.password-store-angleswings/.gpg-id` and see if the recipient is actually in there.

**Comment by funkeyfreak** [comment]
- Alright, that explains the behavior. Any reason why the keys already in the store are failing to decrypt?
- I do not understand either. I included the store in the remove recipients \- ```gopass recipients remove --store=angelswings <gpg-id>```, yet it still gives me the ```recipient not in store``` error.  If I run ```gopass recipiants``` I even see the key in the store:
```golang
gopass
├── angleswings (/Users/georgebailey/.password-store-angleswings)
│   ├── 0x<gpg-id> - George Baley  george@bedfordsucks.com>
```

**Comment by funkeyfreak** [comment]
Have any additional questions @dominikschulz? I'd really like to use your product but this bug is preventing me from doing so.

**Comment by dominikschulz** [comment]
Thanks for the follow up. Actually this is a little hard to debug from here, but I suspect some "key selection" issue.

You seem to be using the email address as the GPG identifier?
Could you please try to use the GPG ID (hash / fingerprint) in all places?
If that works I can narrow this down.

**Comment by dominikschulz** [comment]
@funkeyfreak I was able to reproduce and fix the behavior you described, but I don't know if this actually fixes your bug. If you could try out #436 and confirm or deny this would be awesome.
