### ISSUE TITLE
Documentation for gopass <--> gopassbridge browser plugin setup

### ISSUE THREAD

**Issue by martinhoefling** [justwatchcom/gopass#415]
I've published a new version of the [gopassbridge](https://github.com/martinhoefling/gopassbridge) plugin for firefox and chrome. I would consider the combination of plugin and gopass as beta. So it should work for most users/ cases. I just wonder where to place the documentation how to set up gopass with the corresponding browser plugin?

candidates are:
a section in [docs/setup.md](https://github.com/justwatchcom/gopass/blob/master/docs/setup.md)

a separate file, e.g. docs/browser.md, linked from setup.md

Possible entrypoints for the user are

1. User installs gopass plugin and looks for further documentation to set up native messaging app
-> link to github repo, e.g. section in setup.md
2. User visits https://www.justwatch.com/gopass
-> setup.md is already linked
3. User visits the github repo
-> setup.md is already linked
4. User has gopass installed
when `gopass jsonapi [-help]` is called, also print out a link to the documentation, e.g. section in setup.md

What are your thoughts about this? 

I would also prefer to install the wrapper script outside of `$PATH`, since the wrapper prevents the first tabbing for autocompletion. How about placing the wrapper alongside with the configuration or manifest? In both cases, it would guarantee that the target directory is writeable for the user, e.g. if your're performing a non-global installation.

**Comment by dominikschulz** [comment]
After #416 is merged: Is there anything else left to do?

**Comment by martinhoefling** [comment]
No, let's close it for now.
