### ISSUE TITLE
Rename Makefile LDFLAGS

### ISSUE THREAD

**Issue by notandy** [justwatchcom/gopass#42]
Hi,

Gentoo and Arch inject custom LDFLAGS targeted for binutils-ld that will fail with the golang compiler, please rename the LDFLAGS variable in the Makefile to mitigate this.

Thanks :)

**Comment by metalmatze** [comment]
Yes, I had to overwrite those for Arch as well.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gopass-git#n30

**Comment by dominikschulz** [comment]
Ok, didn't think of that before. We can rename the variable.

Any suggestions?

**Comment by metalmatze** [comment]
I would just prepend GO. So GOLDFLAGS, but I'm fine with anything else too.
