### ISSUE TITLE
Autocomplete for YAML keys in secrets

### ISSUE THREAD

**Issue by bumi** [justwatchcom/gopass#420]
It would be super helpful to have auto-completion for YAML keys in secrets.

Currently the user needs to know the exact name of the YAML key to be able to copy the value to the clipboard. If the key is not known the user has to first display the whole secret to lookup the key. 

Possible usage: `gopass show path/to/secret <tab>` similar to `gopass show <tab>`

If we think that is interesting and possible to implement I'd be happy to look into it.

**Comment by bumi** [comment]
maybe displaying the keys if the user tries to access a non-existent key would also be helpful?

**Comment by dominikschulz** [comment]
That should be possible, but it would need the secret to be decrypted for the autocompletion. I don't like that idea.

**Comment by bumi** [comment]
true, I agree! :disappointed: 
would an optional, separate catalog of keys somehow make sense?

**Comment by dominikschulz** [comment]
Right now we treat anything in a secret as ... secret. So storing the keys somewhere else would violate this contract.

**Comment by bumi** [comment]
totally agree, that's why I thought about it being optional. 
but you're right, the downsides are greater that the advantages.
