### ISSUE TITLE
Moving to an MIT licensed OTP library?

### ISSUE THREAD

**Issue by qbit** [justwatchcom/gopass#422]
I am looking at unifying the OTP interface. Having to specify TOTP or HOTP is no fun. A better alternative is to have a generic `otp` action that works with either. This is how [browserpass](https://github.com/dannyvankooten/browserpass) does it.

I haven't started writing any of the code because I wanted to get opinions on switching to [gokyle/twofactor](https://github.com/gokyle/twofactor). My reasons for wanting to switch are:
- MIT licensed 
- Fewer 3rd party dependencies (only one: https://godoc.org/rsc.io/qr)
- Simpler API that has one entry point for HOTP and TOTP.

**Comment by dominikschulz** [comment]
We generally prefer MIT licensed libaries. Having fewer dependencies also sounds good.

If the library you suggested supports the existing OTP use cases we should probably switch to it.
