### ISSUE TITLE
Installation documentation for Linux have an incorrect filename

### ISSUE THREAD

**Issue by mjrider** [justwatchcom/gopass#423]
the installation instructions give the following snipped
```
wget https://www.justwatch.com/gopass/releases/1.5.1/gopass-1.5.1-linux-amd64.deb
sudo dpkg -i gopass_1.5.1_amd64.deb
```
where the file is downloaded as `gopass-1.5.1-linux-amd64.deb`, but the installation expects `gopass_1.5.1_amd64.deb`

this makes copy&pasting the installation instructions fail

**Comment by dominikschulz** [comment]
Thank you very much for reporting this. Has been fixed.
