### ISSUE TITLE
Gopass sync should give more metadata for importing keys

### ISSUE THREAD

**Issue by falschparker82** [justwatchcom/gopass#425]
![screen shot 2017-10-26 at 11 07 18](https://user-images.githubusercontent.com/670772/32044506-0a28b342-ba3e-11e7-967b-93931489e6cb.png)

Steps to reproduce: `gopass sync` with new public key added to any repository

Issue: `gopass` asks me out of the blue if I want to import a new key, but I don't even know who that is (email, fingerprint, etc.)

Answering `yes` is a gamble: I don't know who I'm currently adding and I'm trusting my peers
Answering `no` is probably also not what I want: In 99% of all cases, I do want to add that person too (if I finally know _who_ ;-) ), also otherwise encryption will fail.

Fix ideas: Either more metadata right away (at least email!) or new option [d] for details...

**Comment by dominikschulz** [comment]
Yes, indeed. I noticed this as well but failed to raise an issue so far. Thanks for reporting.

Should be possible with https://godoc.org/golang.org/x/crypto/openpgp#ReadArmoredKeyRing
