### ISSUE TITLE
Support for dmenu 

### ISSUE THREAD

**Issue by metalmatze** [justwatchcom/gopass#43]
@notandy and me just talked and we need this for i3 & dwm, etc...

**Comment by metalmatze** [comment]
Maybe add `gopass completion dmenu` so we don't have to add another file.

**Comment by dominikschulz** [comment]
Please elaborate why we need `dmenu` integration for a CLI application.

**Comment by metalmatze** [comment]
By utilizing dmenu one can copy a secret to the clipboard within dmenu without actually opening and closing a new terminal just to get the password. To support this just a few lines of code are necessary.

**Comment by MazeChaZer** [comment]
The origininal `pass` includes a script for that, it's called `passmenu`

**Comment by metalmatze** [comment]
@MazeChaZer Yes. I'm aware of that one.
Although we don't need everything it does.

Please take a look at #47 for a first draft of our fork.
