### ISSUE TITLE
gopass -c <secret> doesn't auto clear on KDE Plasma5

### ISSUE THREAD

**Issue by ironhouzi** [justwatchcom/gopass#432]
I think `pass` does `qdbus org.kde.klipper /klipper org.kde.klipper.klipper.clearClipboardHistory &>/dev/null`, but I don't see anything like this in gopass..

gopass 1.5.1 (10c2866255a2bfd40cc9f328ed1101d934e11b77) go1.9 linux amd64

**Comment by dominikschulz** [comment]
Thank you for the hint, we will check that.

**Comment by ironhouzi** [comment]
I'm so amazed at how quickly you responded to this. Just tried it out and it works great.

FYI: Plasma5 default clipboard settings have a history of 10 clipboard records and the default `pass`/`gopass` behaviour is to clear the entire record. This is not necessarily bad, since trying to do anyting else can quickly get messy. I don't even know if the plasma5 dbus interface allow for removal of a certain clipboard record and if there is, removing the latest clipboard entry will not necessarily contain the password added by `gopass`.
You might want to inform your KDE users in your documentation.

Thank you so much for your work!

**Comment by dominikschulz** [comment]
Thanks for trying it out already!

I've added a small note to our FAQ about clearing the whole klipper history.
