### ISSUE TITLE
Explicit option to display only password

### ISSUE THREAD

**Issue by mumblez** [justwatchcom/gopass#438]
Just like passing the `-c` allows copying only the 1st line to the clipboard, can we have a way to explicitly only show the password as an enhancement request.

I like to add extra metadata e.g.

```
somepass123
---
project: someproject
region: someregion
...
```

and to use for scripting purposes I'd like to just extract the password.
I know I can use `head -n1` but it would be a little cleaner to just pull out the password like we can pull out the other yaml fields, e.g.

`gopass entry project`
`gopass entry region`
`gopass -c entry # copies just password to clipboard`

As a possible suggestion
`gopass show -o entry # to show ONLY the password`
or
`gopass show -a entry # inversely, require -a to show all yml fields and default to only showing password, might be unpopular`

**Comment by dominikschulz** [comment]
Yes, of course. Let me just give the UX some thought. Once we settle on a good workflow this is super easy to implement.

**Comment by mumblez** [comment]
awesome
