### ISSUE TITLE
Question: sharing a subset of secrets with a recipient

### ISSUE THREAD

**Issue by amietn** [justwatchcom/gopass#439]
Hello,

I've been using gopass for a while now and came up with a new use case where I'm stumped.

My use case is the following:

* I have a password store with 100 secrets inside of it
* There are 5 recipients who can access all secrets
* We would like to add a new recipient such that he can only access 2 or 3 secrets, not all of them

Is this something that is currently possible to achieve with gopass? How?

Thank you

**Comment by dominikschulz** [comment]
At the moment the finest granularity on which you can grant access is a password store. Granting access to part of a store is currently not possible, this is why we introduced the concept of substores.

You can easily create a new substore, move the 2-3 secrets to this new store, and grant access to all recipients.

**Comment by amietn** [comment]
Thank you for your answer!
