### ISSUE TITLE
qrencode functionality

### ISSUE THREAD

**Issue by notandy** [justwatchcom/gopass#44]
qr code generation for passwords, cool would be output on the console like here: https://www.npmjs.com/package/qrcode-console

**Comment by dominikschulz** [comment]
I'm not sure I understand you correctly.

Do suggest we provide a way to encode a secret as an QR Code and display this on the console?

For example:
```
gopass qr foo/bar
[qr code here]
```

**Comment by notandy** [comment]
> Do suggest we provide a way to encode a secret as an QR Code and display this on the console?
Exactly :smile:

**Comment by metalmatze** [comment]
Just to elaborate: @notandy told me yesterday that, because he doesn't have the password-store on his phone, he sometimes generates QR codes to get the password to his phone to login in etc. Right?

**Comment by dominikschulz** [comment]
Cool, I like the idea. Just wanted to know if I understood it correctly.

**Comment by dominikschulz** [comment]
@notandy Could you check if #64 works for you?

**Comment by notandy** [comment]
@dominikschulz Works great!

**Comment by stefan2904** [comment]
For the record, the command is now `gopass --qr foo/bar`
