### ISSUE TITLE
Wizard UI locks up on OpenBSD.

### ISSUE THREAD

**Issue by qbit** [justwatchcom/gopass#445]
Currently [termbox-go has an issue](https://github.com/nsf/termbox-go/issues/167) on OpenBSD. Anything that fires up a wizard type UI causes the terminal to hang. I poked around a few other terminal centric UI apps ([Micro Editor](https://github.com/zyedidia/micro) in this case) and found [tcell](https://github.com/zyedidia/tcell) which awesomely has a termbox compatibility layer! (Unfortunately it isn't MIT licensed)

With the following diff I am able to use Wizard UI components on OpenBSD:

```
diff --git a/utils/termwiz/selection.go b/utils/termwiz/selection.go
index ad29a8e..630e065 100644
--- a/utils/termwiz/selection.go
+++ b/utils/termwiz/selection.go
@@ -6,7 +6,7 @@ import (
 
 	"github.com/justwatchcom/gopass/utils/ctxutil"
 	runewidth "github.com/mattn/go-runewidth"
-	"github.com/nsf/termbox-go"
+	"github.com/zyedidia/tcell/termbox"
 )
 
 func tbprint(x, y int, fg, bg termbox.Attribute, msg string) {
@@ -30,7 +30,7 @@ func GetSelection(ctx context.Context, prompt, usage string, choices []string) (
 
 	termbox.SetInputMode(termbox.InputEsc)
 	const coldef = termbox.ColorDefault
-	_ = termbox.Clear(coldef, coldef)
+	termbox.Clear(coldef, coldef)
 
 	cur := 0
 	for {
@@ -40,7 +40,7 @@ func GetSelection(ctx context.Context, prompt, usage string, choices []string) (
 			return "aborted", cur
 		default:
 		}
-		_ = termbox.Clear(coldef, coldef)
+		termbox.Clear(coldef, coldef)
 		tbprint(0, 0, coldef, coldef, prompt+"Please select:")
 		_, h := termbox.Size()
 		offset := 0
```

Patching termibox-go (as mentioned in the issue tracker) also works though the UI is very sluggish. For the OpenBSD port I will include a diff that does this, but fixing gopass is ideal in my book.

Is everyone set on using termbox-go? Are there other alternatives that might be more compatible?

**Comment by qbit** [comment]
Er, looks like the actual repo for tcell is this one: https://github.com/gdamore/tcell

**Comment by dominikschulz** [comment]
Ok, looks like I need an OpenBSD Test machine as well ;)

Actually I'm neither very proud of the current wizard implementation not do I prefer any specific library. But me and some of my nearby alpha/beta testers like the wizards a lot, so they won't go away.

As long as we retain the functionality we can replace anything to it. Using an MIT licensed lib would be preferred, but anyway license that's compatible would be ok as well.

**Comment by qbit** [comment]
K! Made #446

**Comment by dominikschulz** [comment]
#446 was merged, so this should be fixed.
