### ISSUE TITLE
Integrate gopass into the main Brew repo

### ISSUE THREAD

**Issue by FlorinAndrei** [justwatchcom/gopass#45]
The install [link](https://www.justwatch.com/gopass/#install-macos) for macOS states:

> If you're a Homebrew maintainer by any chance, feel free to pull the formula into the main repo

That's not how it works. I've opened a thread about that on Brew's Community Discussion site...

http://discourse.brew.sh/t/missing-formula-gopass/618

...and I was told this:

> We don't really do formulae requests. If you're interested: could you try and open a pull request? This document should help and we're happy to walk you through anything else.

This is the document they're talking about:

http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html

So it looks like the process needs to be initiated from your side.

**Comment by dewey** [comment]
The linked document says the following, that's why we refrained from opening a pull request:

```
We frown on authors submitting their own work unless it is very popular.
```

**Comment by dewey** [comment]
@dominikschulz Is this still needed? Was digging into that and fixed everything what's needed to pass the Homebrew repo guidelines (`brew audit --new-formula` etc). If yes I'll open a MR on the main Homebrew repository.

**Comment by dominikschulz** [comment]
@dewey Whatever you think makes most sense. If you want to open a PR please go ahead.
Thanks!

**Comment by falschparker82** [comment]
Well... if they just frown on _authors_, with a total diff contribution of 7 lines to gopass, I'm probably qualified to open that pull request as a very minor contributor :D 

Will give the formula a last brushup and do so next week. :seemsgood:

**Comment by falschparker82** [comment]
Or did you do so already @dewey ? Guess you could do so as well if you're already on it.

**Comment by dewey** [comment]
This is resolved for a while now and we are listed in the official core repository (http://formulae.brew.sh/formula/gopass). Thanks to the contributors who updated the formula in the past!

**Comment by dominikschulz** [comment]
Wow, that's cool!
