### ISSUE TITLE
(linux) Use $XDG_CONFIG_HOME for gopass config yml

### ISSUE THREAD

**Issue by notandy** [justwatchcom/gopass#46]
Since this is the default location for config file according to freedesktop configuration specification: 
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by dominikschulz** [comment]
Need to look into how he'd handle the config location on other platforms.

If we find a good way to handle that, we should probably use `$XDG_CONFIG_HOME` on linux to not clutter our users homedirs.
