### ISSUE TITLE
.gpg-id file not respected in sub folder

### ISSUE THREAD

**Issue by Bouke** [justwatchcom/gopass#462]
I have mounted a password store which contains a sub-folder with a `.gpg-id` file. This file is not respected when managing passwords inside this sub-folder.

```
MyMount
|-- .gpg-id
\-- SubFolder
   \-- .gpg-id
```

On another note, I was quite surprised when running `recipients add --store MyMount/SubFolder SOMEKEY` combined with auto sync that it added SOMEKEY to MyMount, not the sub folder without warning (and then pushing the incorrectly rekeyed passwords to the store).

**Comment by dominikschulz** [comment]
FYI: `gopass` only implements partial support of `.gpg-id` files. Please see: https://github.com/justwatchcom/gopass/pull/291

What exactly do you mean by `this file is not respected when managing passwords`?
Encryption should respect sub folders gpg-ids, but `gopass recipients` is not (yet) able to handle those.

We usually prefer mounts over sub folder gpg ids and thus nobody is working on this (as far as I know). If someone is willing to provide a PR that would be very welcome.

**Comment by Bouke** [comment]
When I add a password in `MyMount/SubFolder`, it uses the keys in `MyMount/.gpg-id` instead of `MyMount/SubFolder/.gpg-id`.

**Comment by dominikschulz** [comment]
Ok, thanks for the clarification. This should indeed work. Will try to reproduce.
