### ISSUE TITLE
Question: howto massedit all secrets

### ISSUE THREAD

**Issue by mjrider** [justwatchcom/gopass#468]
Hi,

most `pass` implementations accept 
```
secret
login: username
```

but gopass enforces that the metadata is valid yaml so now i need
```
secret
---
login: username
```

do you know a way to mass edit all secrets instead of doing them one by one by hand.
to add some more challenges to the question, not all secrets are encodes with the same secrets, some folders have different .gpg-id configs

**Comment by dominikschulz** [comment]
At the moment there is no way to mass edit all (many) secrets, but I was already thinking about this when we introduced the document separator.

Do you think having an command that automatically adds the document separator would be sufficient or do you think we should have something more general?

**Comment by mjrider** [comment]
i think that an 'upgrade' feature in this would be much liked feature. Or a config switch to disable the requirement for a document separator. 

personally i dislike the feature where the login name is part of the path instead of being in the file.

mass editing (sed?) all secret files sounds like a cool feature, but i do not see the use case for that.
