### ISSUE TITLE
openbsd: core dump when launching

### ISSUE THREAD

**Issue by jungle-boogie** [justwatchcom/gopass#472]
Hi All,

Simply running `gopass` with the latest master, causes the app to give a coredump.
I don't have go symbols enabled, so the backtrace is useless for you.

```
$ gopass
Abort trap (core dumped)
$
```

I don't seem to have this problem on an ubuntu like system.

**Comment by qbit** [comment]
Are you installing via ports? Also what version of OpenBSD?

**Comment by jungle-boogie** [comment]
Installing via `go get -u github.com/justwatchcom/gopass`

**Comment by jungle-boogie** [comment]
OpenBSD 6.2-current (GENERIC.MP) #220: Fri Nov 17 11:47:01 MST 2017

**Comment by qbit** [comment]
Looks like I was a bit aggressive with the pledging. Diff shortly

**Comment by qbit** [comment]
@jungle-boogie can you try with this diff #473

**Comment by jungle-boogie** [comment]
@qbit, That's good! It works and doesn't coredump.

**Comment by dominikschulz** [comment]
Should be fixed by #473
