### ISSUE TITLE
Instructions for installation on Gentoo are outdated

### ISSUE THREAD

**Issue by Dr-Terrible** [justwatchcom/gopass#476]
The officially documented way to install `gopass` on Gentoo/Linux is throughout the `andy` overlay:

```shell
layman -a andy
emerge gopass
```
except the specified overlay doesn't exist any more:

```shell
# layman -a andy 
 * Adding overlay...
 * Exception: Overlay "andy" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "andy" does not exist.
```

The correct, and updated, instructions are:

```shell
layman -a go-overlay
emerge -av gopass
```

Please, update the docs and web site.

I'll be the official Gentoo's maintainer of the package `gopass` for the time been ;)

**Comment by dominikschulz** [comment]
Thank you very much for taking care of this. The Readme has been updated, website will follow shortly.
