### ISSUE TITLE
Can't edit secret: failed to run editor..

### ISSUE THREAD

**Issue by d3vr** [justwatchcom/gopass#478]
When I try to edit a secret I get this error, each time with a different file name:

``` Error: failed to invoke editor: failed to run editor with /dev/shm/gopass-edit179424118/secret file```

I'm running Arch Linux/Manjaro with the latest version: **gopass 1.6.1** (c4e1803f built from gopass-git in the AUR) and **go 1.9.2 linux amd64**

I tried looking for similar issues here and googling the error, neither of which helped.

Thanks

**Comment by d3vr** [comment]
I found the issue: the **`$EDITOR` variable was not set** which was causing the problem.

It does [say in the docs](https://github.com/justwatchcom/gopass/blob/master/docs/features.md#edit-a-secret) however, that if the `$EDITOR` variable is not set, `vim` will be used by default. That didn't work for me.

I did some investigating:
[action/edit_linux.go](https://github.com/justwatchcom/gopass/blob/master/action/edit_linux.go) is returning `editor` in case the `$EDITOR` variable is not set, and after some searching I found that @dominikschulz said:
> On Linux the user should always get his favourite editor because we check `$EDITOR` and fall back to `editor` **which should be as symlink to the chosen/default editor**.

This is not mentioned in the docs, wouldn't it be more practical/better if vim was actually used by default?

**Comment by dominikschulz** [comment]
Thank you very much for reporting this. Should be fixed by #479. Please report back if that doesn't help.
