### ISSUE TITLE
Running non-interactively gopass should not print search results

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#482]
When using gopass in scripts it should not print automatic search results but instead exit with an handleable error code.

**Comment by frntn** [comment]
@dominikschulz is there a way to simply deactivate this feature at configuration level ? 
( e.g. for interactive and non-interactive sessions )

**Comment by dominikschulz** [comment]
Do you want to have a config flag to reestablish the old behaviour?
Since the referenced commit gopass will no longer print the search results unless to output goes to a terminal.

**Comment by frntn** [comment]
Sorry but I really really hate this "feature" 😄 
So yes I'd like to config flag to reestablish the old behaviour !

And above all that's unix philosophy to be keep control of the behavior of the tools you run.
