### ISSUE TITLE
Onboarding wizard fails to prompt for remote Git URL

### ISSUE THREAD

**Issue by Zamiell** [justwatchcom/gopass#487]
After a fresh install of CentOS 7 and the latest version of gopass, I go through the onboarding wizard, choosing the first option (local store, no team generation).

The final relevant output is below:

```
[init] [local] Initializing your local store ...
Please select a private key for encrypting secrets:
[0] 0xBB47FD147783B3C8 - Zamiell <zamiell@zamiell.com>
Please enter the number of a key (0-0) [0]:
Use Zamiell (zamiell@zamiell.com) for password store git config? [Y/n]:
[init] [local]  -> OK
[init] [local] Configuring your local store ...
Do you want to automatically push any changes to the git remote (if any)? [Y/n]:
Do you want to always confirm recipients when encrypting? [y/N]:
[init] [local]  -> OK
gopass

[root@localhost ~]# gopass generate foo/bar
How long should the password be? [24]:
Warning: git has no remote. Ignoring auto-push option
Run: gopass git remote add origin ...
```

From this warning, it seems obvious to me that the onboarding wizard missed a step. Before gopass prompts the user with `Do you want to automatically push any changes to the git remote (if any)?`, it should instead ask:

```
Do you want to synchronize this password store with a remote Git repository? [Y\n]
```

Then, if yes, prompt for the remote Git URL. And then, only after the user has successfully entered a Git URL, should it ask the question `Do you want to automatically push any changes to the git remote? [Y\n]`

(Because as it stands, this is a useless prompt for a user who does not intend to use any git functionality.)

A final note:: when hiding this prompt from the user, it should default to false.

**Comment by dominikschulz** [comment]
Yes, indeed. This is confusing. The idea of the `local store` option was to not bother the user with any `git` questions, but of course it makes perfect sense to use a git remote without a team.

We'll fix that.
