### ISSUE TITLE
Gopass does not check for the return value of git and/or handle errors gracefully

### ISSUE THREAD

**Issue by Zamiell** [justwatchcom/gopass#489]
I noticed that gopass crashes in #488, producing an ugly 66 line error message to the user.

Gopass should not crash when the git command fails. It should instead say `The git command failed: Blah blah`, forwarding along the helpful output from the git command to the end-user so that they can see why it happened.

It is common practice to handle errors from external commands gracefully via the mechanism of checking for the command's return code. Besides the `git push` part of the onboarding wizard, are there any other instances in the gopass code where checking for the return code from `git` and/or `gpg` is absent? Perhaps a project-wide audit for this needs to occur.

**Comment by dominikschulz** [comment]
Yes, there are several places where errors are (still) forwarded unchecked. We should examine those and try to handle most of them gracefully.

**Comment by qbit** [comment]
So I started working on this a while ago - not sure if it's the correct approach though: https://github.com/qbit/gopass/tree/errorHandler

Basically I added a wrapper around the After returns (need to make one for the Before) as well.. Maybe `cli` has a better injection point? Seems like it should if it doesn't.
