### ISSUE TITLE
"new"/"create" wizard should not prepend secret type to name

### ISSUE THREAD

**Issue by chbiel** [justwatchcom/gopass#490]
When creating a new secret with "new" or "create" wizard the name gets prepended with "pins", "misc" etc.
But this structure totally breaks our structure.

It would be nice if this would be optional and defaults to "not prepend"

**Comment by dominikschulz** [comment]
The `gopass create` wizard was really intended for novel users that have no clue / don't care how to structure their password store.

I was expecting that experienced users with keep using the `generate`/`insert`/`edit`.

Is there any reason why you want to use the wizard instead these commands?

**Comment by chbiel** [comment]
It's easy to use :)
But I understand your comment so invalid ;)

**Comment by dominikschulz** [comment]
This feature is very new and I don't consider it "established", yet. So if you want to propose different default please go ahead.
