### ISSUE TITLE
Gopass should quit immediately if gpg/gpg2 binaries don't exist until #154 is complete

### ISSUE THREAD

**Issue by dragon788** [justwatchcom/gopass#496]
Background info:
I'm playing with getting gopass set up on a Chromebook in developer mode and trying to avoid immediately jumping into Chromebrew just to get a feel for how useful just having `go` on the machine can be without pulling `gcc` into the mix.

I did have to grab and "install" the Chromebrew `git` binary so that `go get gopass` worked, but other than that it's pretty much a blank slate.

Observed behavior:
The issue I'm reporting here is that the messages when first running gopass on this system are misleading, since it claims to be falling back to GPG 1.x even though I have NO `gpg` binary on the system yet, and it lets me try and run the onboarding wizard and gives me the information about the entropy.md, but doesn't fail until I accept the prompt to "Continue" after the note that it might take a while.

Expected behavior:
gopass exits with a message immediately after running if `which gpg` or `hash gpg` fail to find a valid binary in the PATH. You could even just try `gpg --version` or `gpg2 --version` and catch the error from them not being found and if neither is found simply exit.

```chronos@localhost ~/Downloads $ gopass
Warning: Using GPG 1.x. Using GPG 2.0 or later is highly recommended
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n]: y
[init] No useable GPG keys. Generating new key pair
[init] [gpg] Key generation may take up to a few minutes
[init] [gpg] Creating key pair ...
[init] [gpg] WARNING: We are about to generate some GPG keys.
[init] [gpg] However, the GPG program can sometimes lock up, displaying the following:
"We need to generate a lot of random bytes."
If this happens, please see the following tips:
https://github.com/justwatchcom/gopass/blob/master/docs/entropy.md
Continue? [Y/n]: y

Error: exec: "gpg": executable file not found in $PATH
failed to run command: 'gpg [gpg --gen-key]'
github.com/justwatchcom/gopass/backend/gpg/cli.(*GPG).CreatePrivateKey```

**Comment by dominikschulz** [comment]
Good idea. There are a few operations that work without gpg but overall it probably doesn't make too much sense to even start without gpg being available.
