### ISSUE TITLE
Possiblity to choose recipients per treeitem / subtree

### ISSUE THREAD

**Issue by chbiel** [justwatchcom/gopass#498]
I think it would be a very nice feature if I would be able to (i think it's easier) remove recipients from a single tree item or a subtree of my store.
So I can select in more detail which people have access to secrets within my store

**Comment by dominikschulz** [comment]
We decided to implement this only per mount, so you can have a different set of recipients per mount / repo, but not per subtree within a given repo.

We partly support placing .gpg-id files with a different set of recipients in sub repos, but this is only to avoid nasty suprises when sharing repos with vanilla pass, it's not fully supported UI wise.

We support confirming recipients on every encryption operation (if enabled). We could consider extending this simple yes/no query to an interactive recipient editor. This wouldn't be too much work and fit nicely within the existing code structure.

**Comment by tasmo** [comment]
This is the first disadvantage I found in `gopass`. I depend very much on this feature because we share a repo to different users and groups. Although `pass` still can do this and I can use it when I need to change recipients in subtrees.

**Comment by carlosabalde** [comment]
I agree being able to choose recipients per subtree in a single repo would be a killer feature, at least for use cases like the one a my workplace.

Even more, adding one level of indirection and allowing selecting recipients based on previously defined groups would be even better. Currently we implement those features on to of `pass`, but at the end of the day is just a hacky & far far from ideal wrapper.

Subscribing now to the issue just in case this is reconsidered in the future. Thanks for the great work! :)
