### ISSUE TITLE
gopass does not respect PASSWORD_STORE_GPG_OPTS

### ISSUE THREAD

**Issue by janrito** [justwatchcom/gopass#500]
I don't know if this is by design or gopass does it in a different way, but I haven't been able to find any information about it.

An example would be adding this to the default arguments to gpg
```
export PASSWORD_STORE_GPG_OPTS="--armor"
```

from the documentation of pass:
```
PASSWORD_STORE_GPG_OPTS
     Additional options to be passed to all invocations of GPG.
```
https://git.zx2c4.com/password-store/about/

**Comment by dominikschulz** [comment]
We don't support this (or most/all) of the other pass environment variables.

If you have a specific use case we can try to support it.

**Comment by janrito** [comment]
sure, the example I gave is the usecase I have. I'd like the secrets to be encoded in ascii rather than binary.

**Comment by dominikschulz** [comment]
Ok, we'll consider if/how we can support this properly.

**Comment by janrito** [comment]
thanks!
