### ISSUE TITLE
Add OTP support

### ISSUE THREAD

**Issue by Fale** [justwatchcom/gopass#502]
Hi, this is a very nice initiative. Congrats!
I'm today using the classic pass with https://github.com/tadfisher/pass-otp for OTP management.
I think it would be very nice if gopass would be able to support OTPs as well, since that's the only reason why I'm not switching today to gopass!

**Comment by dominikschulz** [comment]
Gopass has OTP support.

**Comment by Fale** [comment]
thanks :). enabling the bash completition would have been a good idea on my side :D
