### ISSUE TITLE
gopass does not respect store flag with git subcommand

### ISSUE THREAD

**Issue by moritzheiber** [justwatchcom/gopass#511]
I'm a little puzzled, because I'm unable to figure out why exactly this isn't working.

I have four separate stores, managed through gopass, but I'm unable to run a `git` command on a single store:

```
$ gopass git --store store-a status
[store-a]Running git status
[store-b]Running 'git status'
[store-c]Running 'git status'
[store-d]Running 'git status'
```

and that's it. No output, nothing.  Am I doing something wrong? What's the `git` subcommand supposed to do now with sub-stores?

**Comment by dominikschulz** [comment]
`gopass git --store=store-a status` is supposed to run `git status` inside of `store-a`.
That doesn't seem to work right now. We'll investigate.
