### ISSUE TITLE
gopass doesn't list existing secrets when ~/.password-store is a symlink

### ISSUE THREAD

**Issue by Dr-Terrible** [justwatchcom/gopass#514]
With the original `pass` tool, I could do this:

```shell
$ mkdir /tmp/test
$ ln -s /tmp/test ~/.password-store
$ pass init test@email.com
$ pass insert golang.org/gopher 
Enter password for golang.org/gopher: 
Retype password for golang.org/gopher:
$ pass ls
Password Store
└── golang.org
    └── gopher
```

But when I replicate the same behaviour with `gopass`, the tool doesn't list the secrets:
```shell
$ mkdir /tmp/test
$ ln -s /tmp/test ~/.password-store
$ gopass init
$ gopass insert golang.org/gopher 
Enter password for golang.org/gopher: 
Retype password for golang.org/gopher:
$ gopass ls
gopass
```

The secrets are correctly stored though, indeed the `gopass show golang.org/gopher` returns the proper password.

**Comment by dominikschulz** [comment]
Ok, this is weird. We didn't support symlinks in stores in the past. We removed that restriction but may have missed some cases. Should be easy to reproduce, will investigate.

**Comment by Dr-Terrible** [comment]
> We didn't support symlinks in stores in the past.

Yes, I'm aware of the "init --nogit" && "config path ~/path" commands. It just happened that I was upgrading an old box which used `pass` and didn't notice the sym-link until `gopass` screwed royally with my credentials. Happenstance :D 

I'm pretty sure this behaviour will hit more people since the sym-link is quite common among pass's users.

> Should be easy to reproduce, will investigate.

Thank you. Obviously, it's a low priority bug and I have already fixed my set up, no need to fret over it.
