### ISSUE TITLE
Problem with pull and sync with Github

### ISSUE THREAD

**Issue by p3p1** [justwatchcom/gopass#527]
I read a lot of issue (both closed and open) but I still have problem to pull and sync my password store. Just to be clear I have two GPG keys (one is with a Yubikey) and the other that I use with Android app. I add the remote origin in this way:
`git init --store ~/.password-store
git remote add origin git@github.com:myuser/myrepo.git`

But with command **gopass sync** I have the following error: 

`Failed to push '<root>' to it's remote: failed to run command /usr/local/bin/git [git push origin master]: exit status 1`

Possible fix?

**Comment by dominikschulz** [comment]
Please run `GOPASS_DEBUG=true gopass sync` and `cd ~/.password-store && git pull origin master` and provide the, possibly obfuscated, output. There is some issue with git and from your report I can't tell what's wrong. It could be missing remote, but I'm not sure.
