### ISSUE TITLE
git subcommand doesn't allow for interactive actions on stores

### ISSUE THREAD

**Issue by moritzheiber** [justwatchcom/gopass#528]
For some reason I'm unable to do anything meaningful with the `git` subcommand, I'm only getting the command output from `gopass`, but not from the command itself I have run. For example, I would expect `gopass git --store some-store log -p` to give me a itemized list of commits on the relevant store along with the changes, but instead the output is just:

```sh
$ gopass git --store some-store log -p
[some-store] Running 'git log -p'
$
```

It would be good to be able to make use of the built-in git functionality in other ways than just `push` or `pull`, and to receive output feedback from the command itself.

**Comment by dominikschulz** [comment]
Thank you for reporting this issue. I was also curious about the missing output but didn't raise an issue so far. The output redirection seems to be wrong. Will investigate.
