### ISSUE TITLE
gopass -c <search> doesn't copy secret to clipboard

### ISSUE THREAD

**Issue by moritzheiber** [justwatchcom/gopass#531]
It used to be that `gopass` was capable of copying whatever you were searching for to the clipboard afterwards, i.e.:

```sh
$ gopass -c something
Entry 'something' not found. Starting search...
<search-model-selection>
<selection-confirmation>
Copied i/was/looking/for/something to clipboard. Will clear in 45 seconds.
$
```

Now the `-c` switch doesn't seem to have any effect anymore, rather it outputs the secret directly to the console and exits:

```sh
$ gopass -c something
Entry 'something' not found. Starting search...
<search-model-selection>
<selection-confirmation>
i/was/looking/for/something
this_is_secret
$
```

Has this changed recently? Or is it intended behavior?

**Comment by dominikschulz** [comment]
If you run `gopass -c something` and there is no exact match you should see an interative search dialog which prompts you to select a secret.

On the bottom there should be an info line which explains the available operations:
`<↑/↓> to change the selection, <→> to show, <←> to copy, <s> to sync, <ESC> to quit`.

If you hit enter or press → the secret will be shown. If you press ← the secret will be copied to the clipboard (not the primary selection, if using X11).

Is this the use case you're talking about? In that case I'm not able to reproduce.

**Comment by moritzheiber** [comment]
I see, then I'd say it's a little misleading, as the `-c` implies that you want you password copied to your clipboard, or wouldn't it?

I understand the UI approach, but the UX is a little differentiating. I would also be in favor of keeping the switches' behavior intend intact, but that's just me.

**Comment by dominikschulz** [comment]
I think it would make sense to make the default behaviour (i.e. when hiting enter) match the command line switches. That's what you're suggesting, isn't it?

**Comment by moritzheiber** [comment]
Yes, I think that’d be an appropriate solution :)
