### ISSUE TITLE
Vendored semver prevents from using as lib

### ISSUE THREAD

**Issue by raphink** [justwatchcom/gopass#532]
I'm having problems building https://github.com/camptocamp/terraform-provider-pass because of the semver vendoring:

```go
act, err := action.New(ctx, config.Load(), semver.Version{})   
```

results in:

```shell
$ go build .
# github.com/camptocamp/terraform-provider-pass/pass
pass/provider.go:49:59: cannot use "github.com/blang/semver".Version literal (type "github.com/blang/semver".Version) as type "github.com/justwatchcom/gopass/vendor/github.com/blang/semver".Version in argument to action.New
GNUmakefile:7: recipe for target 'build' failed
make: *** [build] Error 2
```

Is there a way to make it so that `action` can be used as a lib (it used to work)?

**Comment by dominikschulz** [comment]
Welcome to the wonderful world of vendoring.
You can either manually remove the vendor folder from gopass (not really practical) or just make sure the consuming project vendors all the necessary dependencies.

**Comment by raphink** [comment]
Ha ha, love the label! Thanks for the pointer.
