### ISSUE TITLE
Possibility to complete aliases

### ISSUE THREAD

**Issue by Fale** [justwatchcom/gopass#535]
Hi,
I have the auto-completion working on the `gopass` command. Due to historical reasons, I use a `pass` alias to the `gopass` command. I would like to be able to create gopass completion also for the `pass` command.
I think a good syntax for this would be `gopass completion bash pass`

**Comment by dominikschulz** [comment]
Bash completion isn't exactly my strength.
Maybe we could add an optional switch that would alter the program name in the generated completion script.

**Comment by Fale** [comment]
Bash completion is not my strength either, and I was thinking the same approach :).

**Comment by kifirkin** [comment]
It seems that it doesn't work for `zsh` completeons :sweat:
