### ISSUE TITLE
How do I use 'gopass init --store'?

### ISSUE THREAD

**Issue by bbigras** [justwatchcom/gopass#54]
I used `gopass init --store test` but I don't know what the value "test" is used for.

**Comment by dewey** [comment]
That's the name of the password store:

```
				cli.StringFlag{
					Name:  "store, s",
					Usage: "Set the sub store to operate on",
```

**Comment by brunoqc** [comment]
I know it's supposed to be the name of the store.

I mean I I don't see it when I run `gopass` nor if I check ~/.gopass.yml or grep ~/.password-store. It seems the value is not used.

Maybe it's related to the warning:
> WARNING: Initializing new stores while mounting is currently not possible. For the time-being you can only mount existing stores.

**Comment by dominikschulz** [comment]
We need to clarify the substore behaviour in the docs.
