### ISSUE TITLE
Feature request: `Sync before` command line switch

### ISSUE THREAD

**Issue by falschparker82** [justwatchcom/gopass#543]
I've had the issue multiple times that I wanted to access a secret, but I didn't know at the time if it has been pushed from another side before and so I always did a double take of `gopass sync` and then `gopass {whatever}` afterwards. 

My idea was to have a new command line switch `-s` // `--sync-before` that blindly executes `gopass sync` before parsing the original request and executing it.

Don't know if it's possible easily with the current code architecture. Thoughts?

**Comment by dominikschulz** [comment]
Good idea!

**Comment by dominikschulz** [comment]
Please note that the current implementation only works with `gopass show -s some/secrect` , not `gopass -s some/secret`.

Let me know if this helps.
