### ISSUE TITLE
Unable to build gopass

### ISSUE THREAD

**Issue by kepi** [justwatchcom/gopass#550]
There is documentation about contributing in https://github.com/justwatchcom/gopass/blob/master/CONTRIBUTING.md

It seams that it isn't enough to just `go build` as I get dependency warnings. I understand that if I want to contribute, I should probably be able to get around it and install deps. I think that my general programming skills are high enough to make small contributions a but I don't want to learn whole Go ecosystem only because I want to fix my favorite tool :)

Please update documentation so it is easy to build gopass after making changes and test them.

If I'm blind only, please give me some suggestion. I spent almost hour searching how dependencies should be installed but found nothing.

```
~/dev/os/gopass master*  
❯ docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:stretch go build -v
main.go:15:2: cannot find package "github.com/blang/semver" in any of:
	/usr/local/go/src/github.com/blang/semver (from $GOROOT)
	/go/src/github.com/blang/semver (from $GOPATH)
main.go:16:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/go/src/github.com/fatih/color (from $GOPATH)
main.go:17:2: cannot find package "github.com/justwatchcom/gopass/action" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/action (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/action (from $GOPATH)
main.go:18:2: cannot find package "github.com/justwatchcom/gopass/backend/gpg" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/backend/gpg (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/backend/gpg (from $GOPATH)
main.go:19:2: cannot find package "github.com/justwatchcom/gopass/config" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/config (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/config (from $GOPATH)
main.go:20:2: cannot find package "github.com/justwatchcom/gopass/store/sub" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/store/sub (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/store/sub (from $GOPATH)
main.go:21:2: cannot find package "github.com/justwatchcom/gopass/utils/ctxutil" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/utils/ctxutil (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/utils/ctxutil (from $GOPATH)
main.go:22:2: cannot find package "github.com/justwatchcom/gopass/utils/out" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/utils/out (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/utils/out (from $GOPATH)
main.go:23:2: cannot find package "github.com/justwatchcom/gopass/utils/protect" in any of:
	/usr/local/go/src/github.com/justwatchcom/gopass/utils/protect (from $GOROOT)
	/go/src/github.com/justwatchcom/gopass/utils/protect (from $GOPATH)
main.go:24:2: cannot find package "github.com/mattn/go-colorable" in any of:
	/usr/local/go/src/github.com/mattn/go-colorable (from $GOROOT)
	/go/src/github.com/mattn/go-colorable (from $GOPATH)
main.go:25:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/local/go/src/github.com/urfave/cli (from $GOROOT)
	/go/src/github.com/urfave/cli (from $GOPATH)
main.go:13:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
```

**Comment by dominikschulz** [comment]
Hi, thanks for trying to contribute. The documentation looks correct.
All dependencies are vendored correctly, otherwise the CI builds would not pass.
It seems that you didn't setup you `$GOPATH` correctly.

If you run `docker run --rm -v "$PWD":/go/src/github.com/justwatchcom/gopass -w /go/src/github.com/justwatchcom/gopass golang:stretch go build -v` it should work.

**Comment by kepi** [comment]
Ok, looks like I should take a break today instead of working :) I didn't realize that `/usr/src/myapp` is supposed to be real path, just thinking that `/usr/src/myapp` is default for building in docker. Thanks @dominikschulz working without any trouble.

I think it would be great to add "docker way" to contributing documentation. Should I create PR or it is not good idea?

**Comment by dominikschulz** [comment]
That would be very welcome, please go ahead.

**Comment by samzilverberg** [comment]
i also had trouble building jsut following the contrubuting guide.
but going into the docker image and doing `go env` and comparing that and the folder structure with my local non-docker one (on mac) helped a lot.

what worked for me finally is:
- setting $GOPATH to $HOME/go-workspace
- mkdir  $GOPATH/src
- mkdir -p $GOPATH/src/github.com/justwatchcom/
- cloning gopath project the the above dir (so its in $GOPATH/src/github.com/justwatchcom/golang)
- making sure $GOROOT points to /usr/local/opt/go/libexec/ (installed golang via brew)
- then i could cd into the gopass dir and sucesfully `go build -v`

^^ this IMO can be reflected in contributing.md

**Comment by samzilverberg** [comment]
FYI: `make test` is not working on mac, but works in the linux based docker container.
because [edit_test.go](https://github.com/justwatchcom/gopass/blob/07269db227e916927ee7b933f8df95df039f8091/action/edit_test.go#L60) tries to use `/bin/touch` which is located on `/usr/bin/touch` on mac.

maybe worth calling `which touch` somewhere before? ;)

**Comment by dominikschulz** [comment]
With recent Go releases (1.9+) it should be a lot easier since they started to default to a `$GOPATH` of `$HOME/go` in case `$GOPATH` is not set.

We should probably add a hint to use at least Go 1.9 to build gopass. I'd also like to extend the Docker support / instructions. If anyone wants to help, that would be perfect, otherwise I'll tackle this once I got some time.

**Comment by samzilverberg** [comment]
https://github.com/justwatchcom/gopass/pull/556 adds some helpful info to contributing.md file from this issue.

**Comment by samzilverberg** [comment]
@kepi check out the new documentation, especialy CONTRIBUTING.MD

**Comment by kepi** [comment]
I thought somebody else would close the issue but I will as new documentation is great. Thanks!
