### ISSUE TITLE
Terminal UI is flaky on MacOS

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#564]
Using `gopass create` on MacOS is flaky, i.e. after choosing the type of secret to create one has to hit enter before one can enter an URL. This works on Linux.

**Comment by qbit** [comment]
Dang - this re-introduces the breakage on OpenBSD.

**Comment by dominikschulz** [comment]
I'm sorry, didn't think about that. We'll handle this in #587.
