### ISSUE TITLE
Issues with gpg keys

### ISSUE THREAD

**Issue by oren** [justwatchcom/gopass#581]
I noticed something interesting. If I let gopass create gpg key, it's not showing up in `gpg --list-secret-keys`. Because of that and also because I decided it's better for me to learn how to create and manage gpg keys myself I rm -r ~/password-store, generated gpg keys using 'gpg --gen-key' and run `gopass init'. The problem I noticed is it's not recognizing the gpg key I created and instead it only recognized the gpg key that was created previously using gopass.

I have the following questions:
1. How to delete the key that was created using gopass?
1. How to use the gpg key I created outside of gopass?

**Comment by dominikschulz** [comment]
This may be an issue with GPG 1.x vs 2.x. In recent GPG versions the format and location of the secret keyring changed. Depending on your exact setup you may be invoking GPG 1.x or GPG 2.x when running `gpg` on the command line. gopass will always try to invoke GPG 2.x, so this is were the confusion might arise.

You should try listing the keys for GPG 1.x and GPG 2.x (if installed):
```
gpg -K
gpg2 -K
```

**Comment by oren** [comment]
Thank you. Let me know if this helps:
```
gpg -K
/home/oren/.gnupg/secring.gpg
-----------------------------
sec   2048R/16774050 2017-12-30
uid                  Oren Golan <orengolan@gmail.com>
ssb   2048R/3262BC95 2017-12-30

gpg2 -K
/home/oren/.gnupg/pubring.gpg
-----------------------------
sec   rsa2048/DC4C0C24 2017-12-26 [SC]
uid         [ultimate] Oren Golan <orengolan@gmail.com>
ssb   rsa2048/7E28F912 2017-12-26 [E]
```

**Comment by dominikschulz** [comment]
Thanks, this looks exactly like what I had in mind, i.e. a mixed GPG 1.x/2.x setup. You should migrate your keys to 2.x and alias `gpg2` to `gpg`. Unfortunately this is beyond the scope of what we can cover here, but there should be plenty resources online.
