### ISSUE TITLE
Terminal issues from #446 have resurfaced because of #562

### ISSUE THREAD

**Issue by qbit** [justwatchcom/gopass#587]
Looks like gocui uses termbox-go under the hood. As described in ~#446~ #445, there is an [issue](https://github.com/nsf/termbox-go/issues/167) with this lib on BSDs.

I looked briefly at switching gocui to use the tcell lib, seems tcell is missing some mouse handling stuff..

**Comment by dominikschulz** [comment]
The problem is that the other lib breaks MacOS and I'd rather break OpenBSD than Mac (sorry, but due to the number of users on each system ...)

**Comment by qbit** [comment]
Makes sense.. Maybe we can have it pick a lib depending on `+build` directives? Or maybe it's worth adding a feature that completely disables the UI?

**Comment by dominikschulz** [comment]
Actually I saw this coming and wanted to include some option before releasing 1.6.7 but forgot about it.
We'll release a hotfix as soon as you confirm it works on OpenBSD and later on can look for a proper solution.

**Comment by qbit** [comment]
Can confirm, #588 fixes the terminal issues on OpenBSD!

**Comment by dominikschulz** [comment]
Thanks for checking! Will try to schedule another bugfix release ASAP.
