### ISSUE TITLE
name collision with  https://github.com/cortex/gopass

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [justwatchcom/gopass#59]
Could you guys please figure out who changes the name

Referred by https://github.com/cortex/gopass/issues/31

**Comment by dominikschulz** [comment]
I don't think this is a problem, since `github.com/cortex/gopass != github.com/justwatchcom/gopass`.

**Comment by falschparker82** [comment]
Nobody. Why?

**Comment by cortex** [comment]
@morriswinkler-simplesurance Yes, this situation is unfortunate, and gopass wasn't such an awesome in the first place :D. Also, github.com/justwatchcom/gopass has some overlap with the support functions I have built here to make the client work. I'll see if it is possible to make this work better together somehow.
