### ISSUE TITLE
'create' subcommand presents creation options in wrong order

### ISSUE THREAD

**Issue by jeevers** [justwatchcom/gopass#593]
I am running the current master branch, installed using 'go get github.com/justwatchcom/gopass'

When I run  'gopass create' I'm presented with this list:
```
┌───────────────────────────────────────────────────────────────────────────────┐
│gopass                                                                         │
│Please select the type of secret you would like to create                      │
└───────────────────────────────────────────────────────────────────────────────┘
 Website Login
 PIN Code (numerical)
 Generic
 AWS Secret Key
 Google Service Account
┌───────────────────────────────────────────────────────────────────────────────┐
│<↑/↓> to change the selection, <→> to select, <ESC> to quit                    │
└───────────────────────────────────────────────────────────────────────────────┘
```

The first two options work as expected, however choosing `Generic` brings up:
`Please enter the AWS Account this key belongs to []:`

Choosing `AWS Secret Key` outputs:
`Please enter the AWS Account this key belongs to []:`

And `Google Service Account` brings up:
`Please enter a name for the secret []:`

I have traced the problem to `actions/create.go` specifically where the `types` slice is defined:

```golang
	types := []string{
		"Website Login",
		"PIN Code (numerical)",
		"Generic",
		"AWS Secret Key",
		"Google Service Account",
	}
```

I think the easy fix would be to move `Generic` to the end of the list so it matches the order of  case structure:

```golang
	types := []string{
		"Website Login",
		"PIN Code (numerical)",
		"AWS Secret Key",
		"Google Service Account",
		"Generic",
	}
```

**Comment by dominikschulz** [comment]
Thank you very much for taking the time to report this issue. If I can reproduce it, it'll be fixed shortly.

**Comment by sioked** [comment]
@dominikschulz Can you publish this to homebrew? I'm seeing this issue on the latest published homebrew version. Thanks!

**Comment by dominikschulz** [comment]
I'm sorry, but I'm not involved with the homebrew recipe. Maybe someone else can help here @dewey @falschparker82 ?

**Comment by dewey** [comment]
I'll see what's needed for that. It's usually done by other users that create the pull requests there but there's always some delay until our release gets merged into homebrew.
