### ISSUE TITLE
Support for ECC Keys

### ISSUE THREAD

**Issue by rays** [justwatchcom/gopass#600]
Elliptic-curve crypto keys are typically smaller than the 1024 minimum gopass is expecting, so gopass rejects these types of keys.

It would be great to see ECC supported in gopass going foward

**Comment by dominikschulz** [comment]
Where exactly are we enforcing this limit? I don't think we should enforce any artificial key size and I didn't think we'd do so.

**Comment by rays** [comment]
https://github.com/justwatchcom/gopass/blob/b22f8044fdac76b7782bc437a7fbd6f7983d4bd4/store/sub/gpg.go#L115-L117

**Comment by dominikschulz** [comment]
Ok, thank you. That's an oversight, we'll adjust this accordingly.

**Comment by dominikschulz** [comment]
This should be fixed: https://github.com/justwatchcom/gopass/commit/72000bd753413f7160edc4e8e91460ef586397cc#diff-d67bf8c21fa1e166d48546a81ffb005aR116
