### ISSUE TITLE
backspace gives different character

### ISSUE THREAD

**Issue by deltaskelta** [justwatchcom/gopass#608]
when entering input on stdin backspace gives a different character...

`^H^H^H` is what is added to the stdin when I hit backspace on MacOS
```
$ gopass new
Creating generic secret ...
Please enter a name for the secret []: foo^H^H^H
```

**Comment by dominikschulz** [comment]
This is strange, will try to reproduce on MacOS.

**Comment by deltaskelta** [comment]
```
MacOS 10.13.2

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by deltaskelta** [comment]
I figured out the problem...sort of 

I was using iterm2 and if I manually entered the character `^?` it acted as a backspace. the normal mac terminal backspace acts as expected.
