### ISSUE TITLE
homebrew + gnupg 21

### ISSUE THREAD

**Issue by danilobuerger** [justwatchcom/gopass#61]
Since I can't open an issue at https://github.com/justwatchcom/homebrew-gopass, I am opening this here:

Would it be possible to also allow gnupg 21 as a dependency instead of gnupg 2 only?

**Comment by danilobuerger** [comment]
To clarify this: gopass works perfectly for me with gnupg 21. However, I must install it via go get instead of brew to circumvent the dependency of gnupg 2.

**Comment by falschparker82** [comment]
Hey - I've dug a little into this issue, but I have no real solution for it.

Unfortunately, `gnupg`, `gnupg2` and `gnupg21` seem to be completely different and mutually incompatible packages for homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnupg2.rb
```
class Gnupg21 < Formula
[...]
  conflicts_with "gnupg2",
:because => "GPG2.1.x is incompatible with the 2.0.x branch."
```

While `gopass` should work fine with either version, I didn't find any option to specify _any GPG package_ as a dependency.

I've filed an issue with the homebrew community here: http://discourse.brew.sh/t/write-formula-to-work-with-any-version-of-gpg/662

**Comment by danilobuerger** [comment]
Maybe using an option would work:
http://stackoverflow.com/a/28738539/2525941

**Comment by falschparker82** [comment]
...a little ugly, but looks reasonable - I'll give it a try

**Comment by danilobuerger** [comment]
I agree! But better than nothing.

**Comment by falschparker82** [comment]
Just updated the formula - would you volunteer to be my guinea pig? (don't want to go to gpg 2.1 right now)

`brew update && brew install gopass --with-gnupg21`

(oh, btw. I've opened the issue tracker at the other repo)

THX and have a nice weekend!

**Comment by danilobuerger** [comment]
Just tried, works for me.

Thanks!
