### ISSUE TITLE
tempdir test case that fails on mac but on linux

### ISSUE THREAD

**Issue by samzilverberg** [justwatchcom/gopass#611]
this test case:

https://github.com/justwatchcom/gopass/blob/d0e25692243aec4830423aa3e80b8bfcc5478410/utils/fsutil/tempdir_test.go#L39-L44

` assert.NoError(t, utf.Remove(ctx))`
on mac this error is returned

https://github.com/justwatchcom/gopass/blob/d0e25692243aec4830423aa3e80b8bfcc5478410/utils/fsutil/tempdir_darwin.go#L76-L79
because t.dev and t.dir are empty (this is the test case, an uninitialized tempfile struct)

on linux its ok because the impl just returns nil
https://github.com/justwatchcom/gopass/blob/d0e25692243aec4830423aa3e80b8bfcc5478410/utils/fsutil/tempdir_linux.go#L32-L33

Maybe you have an idea to fix this so it works on both with the assertion?

FYI when commenting this one assertion out all the rest of the tests pass on mac, KUDUS to you :1st_place_medal: 🏆

**Comment by dominikschulz** [comment]
Thank you very much for reporting this issue. Unfortunately we don't have automated tests on Mac, yet.
I think we should just `return nil` in the `tryUnmount` method on MacOS. I'm working on a PR just now.
