### ISSUE TITLE
Botched setup, but unable to reset or restore

### ISSUE THREAD

**Issue by mhumeSF** [justwatchcom/gopass#626]
I think I messed up my initial setup, but now I cannot init and am getting an error when running `gopass init`
```
No gpg binary found: failed to init root store: checking mounts failed: Doubly mounted path at ...
```

Gpg is installed. I manually removed the `~/.password-store...` locations, so I think this might have something to do with it.

**Comment by dominikschulz** [comment]
Thank you very much for reporting this issue.
This sounds like there are several issues. We'll need your help to help your here.

Please provide the output of the following commands (feel free to redact anything that you deem private):
```
$> gopass version
$> GOPASS_DEBUG=true gopass
$> cat ~/.config/gopass/config.yml
```

**Comment by mhumeSF** [comment]
Thar it be. Updating `~/.config/gopass/config.yml` so it didn't have multiple entires referencing the same remote, fixed things. Thanks! 👍
