### ISSUE TITLE
At is replaced with underscore during 'gopass create'

### ISSUE THREAD

**Issue by novakboskov** [justwatchcom/gopass#636]
When I try to add new record using `gopass create` and insert username that contains `@` it replaces that with a '_' and save it in that changed form. Later, `gopass`, in its tree view, shows username that contains `_` in the place of `@`.

Perhaps I do something wrong or miss a part of documentation?

**Comment by dominikschulz** [comment]
That is intended behavior. Any possibly dangerous characters are replaced with underscores.

**Comment by novakboskov** [comment]
@dominikschulz Thank you. It has been introduced recently? Just few weeks ago I've added few records that included `@` and it is stored in its original form, without any substitutions.
