### ISSUE TITLE
gopass doesn't find gpg on Windows when installed with scoop

### ISSUE THREAD

**Issue by DaanDeMeyer** [justwatchcom/gopass#647]
If I install gpg with scoop (https://github.com/lukesampson/scoop) on Windows, the gpg binary is available in the PATH but gopass can't find it. I looked at the code for finding the gpg binary on Windows and right now it requires gpg to be in the registry (which scoop doesn't modify). 

A possible solution is to also check the PATH for the gpg binary instead of only looking at the registry.

**Comment by dominikschulz** [comment]
Thanks for reporting this issue and the suggestion. I'll see if we can easily check the Path if the registry doesn't contain any GPG entry. Shouldn't be too hard ...

**Comment by DaanDeMeyer** [comment]
Awesome! I'll test this when I have access to my Windows machine.

**Comment by dominikschulz** [comment]
Thanks for testing this!

Unfortunately I still don't have any way to test `gopass` on windows myself.

**Comment by DaanDeMeyer** [comment]
I'll have a look to see if I can find the problem

**Comment by DaanDeMeyer** [comment]
I've found the problem. The detectBinaryCandidates function first tries to open a registry key in order to find the install location but if this returns an error detectBinaryCandidates immediately exits instead of trying to search the path or other install locations.

**Comment by dominikschulz** [comment]
Yes, of course ... that's wrong. Thanks a lot for finding my silly mistake.

**Comment by DaanDeMeyer** [comment]
This is fixed for me now. However, another problem appeared but I'll make a separate issue for that.
