### ISSUE TITLE
Pluggable encryption

### ISSUE THREAD

**Issue by rendaw** [justwatchcom/gopass#653]
I came here after looking at `pass` and seeing `gpg` tossed everywhere.  I have a Trezor which has offloaded encryption and decryption functions exposed via protobuf.  Would this be doable without major refactoring in gopass?  95% of the work I wouldn't want to write myself is git management, bash completion, etc.

**Comment by dewey** [comment]
You could take a look at this PR: https://github.com/justwatchcom/gopass/pull/645

It's adding another crypto backend so gpg wouldn't have to be used. This should give you an idea of the work involved if you want to work on it.

**Comment by dominikschulz** [comment]
@rendaw To do this does actually require a major refactoring, as you can see in the PR @dewey mentioned.

Good things is that it's already being done and should be ready in a few short weeks. After #645 is merged it should be a lot easier (if not trivial) to add a different crypto backend. I have not access to this device but I'd be happy to assist you if you want to contribute a backend for that.

**Comment by rendaw** [comment]
Awesome, I'll watch that.  Thanks @dewey @dominikschulz !

And this is off the cuff so I haven't thought about it much, but if you were interested and had it on an Amazon wishlist I might get it for you.

**Comment by dominikschulz** [comment]
This should be resolved by #645 .
