### ISSUE TITLE
incompatible with lastpass2pass.rb

### ISSUE THREAD

**Issue by fcheslack** [justwatchcom/gopass#66]
Trying to import lastpass credentials using lastpass2pass.rb from https://www.passwordstore.org/
gopass gets confused reading EOF when inserting. Probably because it asks for confirmation.

Trying to go ahead with the confirmation also didn't work for me using something like

    cmd := exec.Command("gopass", "insert", "-f", fmt.Sprintf("%s/%s", "test", "username"))
    cmd.Stdin = strings.NewReader(fmt.Sprintf("%s\n%s\nY\n", "password", "password"))

**Comment by dominikschulz** [comment]
Thanks for reporting this. We need to look into how we deal with STDIN.

**Comment by jkseppan** [comment]
I had the same problem, and got the script to work with #69.

**Comment by metalmatze** [comment]
I guess, now that #69 is merged, we can assume this works now.
