### ISSUE TITLE
Be able to use a different email than ~/.gitconfig

### ISSUE THREAD

**Issue by bbigras** [justwatchcom/gopass#68]
I'm using a different email address with git and gopass. To work around #13 I need to change my email address in ~/.gitconfig. It would be cool to be able to specify a email address when creating a store or maybe use the email address from the selected gpg key.

**Comment by marthjod** [comment]
@bbigras Is this related to #179 maybe? You can set any git email during `init` now.

```
# given a suitable private GPG key --
go run main.go init
...
Use Foo Bar (foo@bar.com) for password store git config? [y/N]: y
Please enter a user name for password store git config [Foo Bar]: 
Please enter an email address for password store git config [foo@bar.com]: other@example.com
...
go run main.go git config user.email
other@example.com
git config user.email
marthjod@gmail.com
```

**Comment by bbigras** [comment]
It's perfect is I can set an email during `init`. Thanks!
