### ISSUE TITLE
Copy to clipboard if there is no safecontent

### ISSUE THREAD

**Issue by AuspeXeu** [justwatchcom/gopass#684]
I just found the option `safecontent` to not display passwords which is quite handy when working in an office where people can see my screen. What I find a bit inconvenient though is that if there is no safe content, I get prompted with a warning. I think it would be nice to copy the password to the clipboard as the user's intention obviously is to use his password in that case.

**Comment by AnomalRoil** [comment]
This is a neat idea, I'll add it later today.
