### ISSUE TITLE
No info about setup wizard in help

### ISSUE THREAD

**Issue by schmunk42** [justwatchcom/gopass#689]
The setup command does not appear when running `gopass -h`

Related: #390

**Comment by dominikschulz** [comment]
So far this is intended. There are already way too many subcommands cluttering the help output and this one is usually not required.

If there is specific reason for this command to show up in the help output we can remove the `hidden` flag.

**Comment by schmunk42** [comment]
Can/should it only be run once? I thought "Join a team" could be possible multiple times.

**Comment by dominikschulz** [comment]
Right now it's designed to be run only once. Of course one might want to use it to join multiple teams, but these use-cases haven't been implemented, yet. I'd like to get there at some point and then it would definitely make sense to expose it as a subcommand, but for now it might be too confusing.

**Comment by schmunk42** [comment]
OK, please close at will.
