### ISSUE TITLE
Fails with "no remote" if remote is named other than origin

### ISSUE THREAD

**Issue by edio** [justwatchcom/gopass#691]
```
[~]$ cd .password-store

[~/.password-store]$ git remote
github

[~/.password-store]$ gopass sync
Sync starting ...
[<root>] 
   git pull and push ... Skipped (no remote)
```

**Comment by dominikschulz** [comment]
Correct, this is limitation the currently exists.
It should be easy to lift this limitation for the trivial case were only one remote exists.
Not sure about a heuristic if multiple exist.

**Comment by edio** [comment]
I'm not aware of how do you interact with git, sorry if my question is off. But shouldn't it be possible if current branch was a tracking branch? In git CLI for example it's enough to type just `git push` in this case, even if multiple remotes exist.

**Comment by dominikschulz** [comment]
Yes, that is correct. I also thought #692 might be overengineered right after submitting it, but if you haven't properly setup your git remotes a simple `git push` may fail. We want to help our users with that case. Unfortunately simply assuming defaults (origin/master) makes some use cases fail while the lookup logic in #692 duplicates the logic git does by itself.
