### ISSUE TITLE
Windows: "Error: unknown sync backend 'gitmock'

### ISSUE THREAD

**Issue by DaanDeMeyer** [justwatchcom/gopass#694]
Error occurs when cloning repo with gopass (gopass clone <repo>) with git installed through scoop (https://github.com/lukesampson/scoop) and available through the PATH. I'm not really sure where to start looking for a fix for this.

**Comment by dominikschulz** [comment]
This is related to a major refactoring in the 1.7 development cycle. Errors related to the different backends are expected and we plan to track them down before the next release. Sorry for the inconvenience. Will try to fix this soon.
