### ISSUE TITLE
gopass vs hashicorp vault

### ISSUE THREAD

**Issue by prune998** [justwatchcom/gopass#7]
While I see some similarities, what are the main differences ?

**Comment by dominikschulz** [comment]
Short Anwser: Vault is for machines while gopass is for humans.

Will add a longer answer to the README or the FAQ.

**Comment by jefferai** [comment]
This project looks super cool. We are often asked if Vault can do the types of things that gopass does and our general answer is "not really what Vault is meant for". Glad to have another neat project we can point people to in these cases!

**Comment by tehnomaag** [comment]
Vault would be an awesome backend for gopass, to compete with 1Password for Teams for example. Vault can have much more detailed permission rules and also has audit logs on who accessed what/when. Which is much harder or impossible to do with git repos.

**Comment by dominikschulz** [comment]
We are actually already planning on supporting different backends. Vault could make sense as an gopass backend.

**Comment by adamdecaf** [comment]
I'd also think that gopass could be used as the source of truth for secrets put into vault. If you're using a database backend and need to mount it in vault the credentials you give to vault could be stored in gopass.

**Comment by jefferai** [comment]
Yep, or your Vault token, or or or.
