### ISSUE TITLE
error messages on deleting empty folders

### ISSUE THREAD

**Issue by notandy** [justwatchcom/gopass#70]
This could be possibly connected to #55 

deleting an empty folder with gopass rm -r yields an error message, but deletes the folder.

> $ pass edit test/test
> ...
> $ pass rm test/test
> Are you sure you would like to delete test/test? [y/N]: y
> $ pass rm -r test
> fatal: pathspec '/home/andy/.password-store/test' did not match any files
> 
> Error: failed to add files to git: exit status 128

**Comment by metalmatze** [comment]
Still not resolved by #89

**Comment by dominikschulz** [comment]
Confirmed fixed in master.
