### ISSUE TITLE
autosync for sub-store is ignored if root autosync is set to false

### ISSUE THREAD

**Issue by cjeffers** [justwatchcom/gopass#700]
I was trying to add a team password store (mounted as a sub-store). I do not have a personal or local repository, so i did not add a git remote for the local (root) store. I set the mounted team store's autosync to true:

```gopass config --store <team-store> autosync true```

But when inserting/changing secrets in the team store, the changes were not automatically pushed to the team remote. I could manually push them using `gopass git -s <team-store> push`. When I set the root store's autosync to true as well, then the team store automatically pushed to the remote, as expected.

I'm using gopass version 1.6.10

**Comment by dominikschulz** [comment]
Thanks for reporting this. We had this issue before and I thought we fixed it already. Will double check.

**Comment by ayharano** [comment]
Before opening a new issue, I searched if there was one somehow related and this seems to be a tangent case.

I'm also using gopass version 1.6.10 and setup to every store and mounts except one (let's name it `<sub-store>`) to confirm each and every time. However, when I run to insert, it asks for confirmation:

```
$ gopass insert <sub-store>/newsecret
Enter password for <sub-store>/newsecret:
Retype password for <sub-store>/newsecret:
Warning
gopass: Encrypting /newsecret for these recipients:
- 0x0123456789ABCDEF - User Name <email@example.tld>

Do you want to continue? [Y/n]: 
```

Config output:
```
$ gopass config
root store config:
  askformore: false
  autoimport: false
  autosync: false
  cliptimeout: 45
  nocolor: true
  noconfirm: false
  nopager: false
  path: /path/to/root
  safecontent: false
  usesymbols: false
mount 'another' config:
  path: /path/to/another
mount '<sub-store>' config:
  noconfirm: true
  path: /path/to/sub-store
mount 'one-more' config:
  path: /path/to/one-more
```

For me, it seemed to be a related case. If it is not, how to proceed? Open a new issue?

**Comment by dominikschulz** [comment]
@ayharano Indeed, this could be related. For the time being I'd like to track this in this issue. Thanks for reporting it!
