### ISSUE TITLE
feature: fsck option to check a particular mount

### ISSUE THREAD

**Issue by tagirb** [justwatchcom/gopass#711]
As per `gopass fsck --help`, fsck is currently able to 
> Check all mounted password stores for know issues and inconsistencies, like wrong file persmissions or missing / extra recipients.

This may take too much time if many mounts are used (which is my case).

Is it possible to add an option to run fsck against a particular mount?

**Comment by dominikschulz** [comment]
Yes, this definitely possible. Altough I was considering completely removing / rewriting the fsck command since it doesn't really work with anything but filesystem based GPG stores.

**Comment by tagirb** [comment]
Wow, man, I didn't know you had other backends like Vault on your roadmap. Exciting!

As for fsck, although rather simple, it proved to be really helpful. Is it maybe possible to make it specific to the GPG backend?

Generally, thanks a lot for this project! Here at https://labs.reservix.de we're currently integrating it into our workflow. No time to contribute much now due to the workload, but hopefully sometime later.

**Comment by dominikschulz** [comment]
Glad to hear that you like it. So far I didn't even know if anyone was using `fsck`, but if you are we'll keep it for sure.
