### ISSUE TITLE
add/remove recipients to store without via script

### ISSUE THREAD

**Issue by jhartlep** [justwatchcom/gopass#720]
Hi,
I want to use gopass for our team.
One requirement for us is automation. So my approach to this is a bash script running once a day via cron.
Within this script I catch all public keys from the team, sign them locally and then add or remove them to gopass if there are changes.

Everything works fine so far besides adding or removing recipients to gopass.

```
gopass recipients add --store XYZ user@example.org
Do you want to add 'user' as an recipient to the store 'XYZ'? [y/N]: 
```

Is there a parameter like `--yes` in gpg2 to bypass this question?
If not, this would be very helpful!

Best regards,
Jens

**Comment by dominikschulz** [comment]
gopass has a global parameter `--yes` that should be honored by most commands.

**Comment by jhartlep** [comment]
Thanks, found it!
I tried `gopass recipients help`, `gopass recipients add help` but I did not looked at `gopass help`.
Perhaps you should print out the global options from every action help :)

Best regards,
Jens

**Comment by dominikschulz** [comment]
Yes, indeed. We're using the `github.com/urfave/cli` package to do all the CLI heavy lifting. Apparently it doesn't include the global flags on the subcommands by default. If we can change this easily we'll do.
