### ISSUE TITLE
Signing of gopass_X.X.X_SHA256SUMS

### ISSUE THREAD

**Issue by qbit** [justwatchcom/gopass#724]
Would it be possible to have the SHA256SUMS files signed for a given release?

**Comment by dominikschulz** [comment]
Yes, of course. I wonder why we don't do that already.

**Comment by bpicode** [comment]
Do you see a possibility to have multiple persons signing the sha sums? Thinking of reproducible builds here.

**Comment by qbit** [comment]
How would having multiple person sigs help with reproducible builds? Can't you still have a build validated via the single sig?

**Comment by bpicode** [comment]
I was thinking the other way around. Multiple persons reproduce the binaries and express their ability to do so by contributing a sig.

**Comment by qbit** [comment]
I don't think that adds any value that you don't already have in the signed shasum files. Unless I am entirely missing something?

If person A, B and C all get the same shasum that is in the signed shasum file.. then that's the same validation.. minus the extra step of them signing something.

**Comment by bpicode** [comment]
Yes, but its more oriented towards people who don't want to go through the trouble of re-creating the build toolchain. One can still say: "Look, these N people assured the integrity of the package. If you trust one of them you're probably good to go."

**Comment by dominikschulz** [comment]
The reason why we don't do signatures is that our goreleaser branch doesn't support that, yet. It looks like upstream recently added this feature. I'll need to rebase or changes onto their current master and then we should be able to provide signatures. We'll start by signing them using our release key.

@bpicode I'm not sure if I fully understand what you're asking for. Is there any example for what you're proposing?

**Comment by bpicode** [comment]
@dominikschulz There is an analogue in debian, [dpkg-sig(1)](https://manpages.debian.org/jessie/dpkg-sig/dpkg-sig.1.en.html), which allows multiple signatures on a package. However my impression is that it is rarely used and I really struggle to find relevant real-life examples. Maybe I blurted out the idea too early, so no worries ;)

**Comment by dominikschulz** [comment]
I was under the impression that `dpkg-sig` supports this use case for (a) key rollover and (b) the maintainer / developer / builder split. For now I don't really see a compelling case for gopass, but if you manage to find one we can revive this discussion for sure.

**Comment by bpicode** [comment]
FWIW, coyim plans to do https://github.com/coyim/coyim/blob/master/REPRODUCIBILITY.md
