### ISSUE TITLE
rofi completion

### ISSUE THREAD

**Issue by amietn** [justwatchcom/gopass#73]
Add completion support for ```rofi```. You would call ```rofi -dmenu``` with ```gopass completion rofi``` similarly to calling ```dmenu``` with ```gopass completion dmenu```.

**Comment by metalmatze** [comment]
If you're a little experienced with Go I invite you to basically copy what I've done for dmenu and create rofi support. Let me know if you're up to the challenge. :wink:

**Comment by deadc0de6** [comment]
I have done a PR for rofi: #76

**Comment by SevereOverfl0w** [comment]
Would it be better to approach this from the perspective of allowing people to script themselves? Have an option to `list` which prints list of secrets which can be piped into any script the user chooses.

No point trying to wrap up every possibility into gopass. I'd consider the xdotool support to be another example of something that could be moved into a shell script simply by the user.
