### ISSUE TITLE
Number for username

### ISSUE THREAD

**Issue by antoyo** [justwatchcom/gopass#737]
Hi.
I'm not sure if it is the intended behavior or a bug, but here is the issue.
If I have the following YAML:
```yaml
---
username: 42
```
`gopass` won't retrieve this username because it is a number instead of a string.
I need to input the following:
```yaml
---
username: "42"
```
If it is a bug, thanks to fix it.

**Comment by dominikschulz** [comment]
Thank you for reporting this issue. This is not really a bug, but rather a consequence of the YAML specification. This is one of the reasons why we will provide a simpler but more robust K/V Parser.

Thus won't help for certain existing YAML secrets, so I'll look into this. We should be able to make retrieval work in this case.
