### ISSUE TITLE
Generate without symbols

### ISSUE THREAD

**Issue by antoyo** [justwatchcom/gopass#741]
Hi.
I set the config to use symbols to generate the passwords but sometimes I want to generate passwords without symbols because of website limitation.
`pass` has an option `--no-symbols` but `gopass` does not seem to have it.
Could you please add this cli option?
Thanks.

**Comment by dominikschulz** [comment]
Hi,
thanks for reporting this issue. Actually there is a `symbols` flag which can be set to `true` or `false`.
Right now there is a small issue with that flag, but I'll submit a PR to fix it in a second.

**Comment by dragon788** [comment]
@dominikschulz so if the config is set to use symbols, how can you override this from the command line, does passing `-s` which "double sets" symbols toggle it back off when the config file has it enabled?

**Comment by dragon788** [comment]
I think an additional couple of tests in https://github.com/justwatchcom/gopass/blob/master/pkg/action/generate_test.go around the symbols behavior would be excellent as currently it appears there isn't any testing of that functionality.

**Comment by dominikschulz** [comment]
Good idea. We'll add some.

As for your question @dragon788 : The command line switch will override the config option.
See https://github.com/justwatchcom/gopass/blob/master/pkg/action/generate.go#L122 for the implementation.
