### ISSUE TITLE
Get number of words from arguments on xkcd mode

### ISSUE THREAD

**Issue by daniloncmayo** [justwatchcom/gopass#769]
```
root@5663b10922a3:~# gopass generate test/foo2 -x 10
How many words should be combined to a password? [4]:
```

Result Expected: 
Generate a 10 word based passphrase.

Actual behavior:
The number of words are prompted.

I don't have time right now to change/submit a PR right now but it seems a small change.

**Comment by dominikschulz** [comment]
Actually this works as intended except that you seem to be stumbling across a quirk of the CLI library we're using: You have to specify the switches before the arguments, i.e. `gopass generate -x test/foo2 10` should work.
