### ISSUE TITLE
HIBP api in development version not working?

### ISSUE THREAD

**Issue by martinhoefling** [justwatchcom/gopass#772]
I've compiled the current master. Even passwords like `12345` and `allesistsuper` which do show up as [breached in the web query](https://haveibeenpwned.com/Passwords) are not detected. Is this a bug or am I missing something?

**Comment by dominikschulz** [comment]
There are several HIBP modes (API and Dumps). Which one are you using, or rather: Could you provide the exact command you used?

**Comment by martinhoefling** [comment]
Just found the bug, will submit pr in a second :-)
