### ISSUE TITLE
Why is my private key required when I want to init a store

### ISSUE THREAD

**Issue by zachgersh** [justwatchcom/gopass#78]
Hey All,

Great work on the tool, have been experimenting with it a little bit but I was interested in one bit:

https://github.com/justwatchcom/gopass/blob/be6ed5bf4bf0c1dea29699870df814f8f31a85be/action/init.go#L38

I found that I cannot `init` a store without having both my public and private key on the machine. Why does this not work with just my public key?

**Comment by zachgersh** [comment]
hey @dominikschulz - does this mean that you will be switching this around before 1.0.2 or just answering the question in the 1.0.2 milestone. I'd be open to doing a PR as well to fix this.

**Comment by dominikschulz** [comment]
I'd like document this behaviour for the 1.0.2 release.

**Comment by zachgersh** [comment]
@dominikschulz can it be changed? I'd love to know how if I only need the public key to start the initial encryption?
