### ISSUE TITLE
Document usage with gnupg 2.1

### ISSUE THREAD

**Issue by danilobuerger** [justwatchcom/gopass#79]
As per #61 it's now possible to install gopass with homebrew and gnupg 2.1. This should probably be documented.

**Comment by falschparker82** [comment]
Good one - but where? Serious question. Homebrew options are "self-documenting", but tbh they're a little hard to discover when faced with a differing version. Don't know.

**Comment by danilobuerger** [comment]
Why not in the README.md next to the other brew install command?

**Comment by falschparker82** [comment]
As per http://discourse.brew.sh/t/write-formula-to-work-with-any-version-of-gpg/662 I'll probably rewrite the current hack to be a Homebrew::Requirement, which is then really self-documenting.

I'll leave some sample code here for myself later on...
```
class Erlang18Requirement < Requirement
  fatal true
  default_formula "erlang"

  satisfy do
    erl = which("erl")
    next unless erl
    `#{erl} -noshell -eval 'io:fwrite("~s", [erlang:system_info(otp_release) >= "18"])' -s erlang halt | grep -q '^true'`
    $?.exitstatus.zero?
  end

  def message; <<-EOS.undent
    Erlang 18+ is required to install.

    You can install this with:
      brew install erlang

    Or you can use an official installer from:
      https://www.erlang.org/
    EOS
  end
end

[...]
  depends_on Erlang18Requirement
```

**Comment by danilobuerger** [comment]
It seems like the versions tap has been deprecated. http://docs.brew.sh/Versions.html

Maybe now it's possible to depend on something without specifying the version?

**Comment by dragon788** [comment]
I believe per another comment here or elsewhere that they have deprecated gnupg version 1 and gnupg@2.x and replaced the `gnupg` namespace with 2.1.

**Comment by dominikschulz** [comment]
As we strongly suggest / require gpg2 by now, I don't think there are any special cases left to document here.
