### ISSUE TITLE
Password store path in the config file strips "~"

### ISSUE THREAD

**Issue by mariusor** [justwatchcom/gopass#801]
In my config file I have the path to the password store as:

```
root:
  path: gpgcli-gitcli-fs+file://~/.local/share/password-store
```

The 1.7.0 version stopped recognizing it as the "home" path and it strips it.

The exact error is: 

```
Error: failed to list store: lstat /.local/share/password-store: no such file or directory
```

**Comment by dominikschulz** [comment]
Thank you for reporting this issue!
Would be nice if you could give it a try after #802 is merged, then we can build a quick bugfix release.

**Comment by mariusor** [comment]
Built on archlinux `gopass-git r587.80e251f-1` and I can confirm that it works again with ~ in the path of the password store.

**Comment by dominikschulz** [comment]
Ah, thanks a lot. We'll issue a Bugfix release soon.
