### ISSUE TITLE
Feature Request - Fish Shell Completion

### ISSUE THREAD

**Issue by willpatera** [justwatchcom/gopass#84]
## Feature request

Fish shell autocomplete with `gopass completion fish`

Fish shell completion script already exists for pass [here](https://git.zx2c4.com/password-store/tree/src/completion/pass.fish-completion).

Is this feature something that the contributors/community would be interested in adding?

**Comment by metalmatze** [comment]
We personally don't use fish. If someone creates a PR we will definitely consider to add it to gopass. But we're not going to implemented that ourselves.

**Comment by falschparker82** [comment]
I had a first look - syntax and structure looks at least considerably different enough to zsh/bash that it's not trivial to add. Added `help wanted` label in case there's a fish pro wanting to jump in.
