### ISSUE TITLE
release in Brew is old

### ISSUE THREAD

**Issue by FlorinAndrei** [justwatchcom/gopass#92]
1.0.2 has been released last week. However, the version in Brew is still 1.0.1

```
brew tap justwatchcom/gopass
brew install gopass
```

```
$ gopass --version
gopass 1.0.1 (e3c63f0e 2017-03-27 21:23:02) go1.8
```

**Comment by niels-s** [comment]
@FlorinAndrei I've created a PR to address this issue: https://github.com/justwatchcom/homebrew-gopass/pull/1

**Comment by dominikschulz** [comment]
We've updated our release process to automatically push an update to our brew tap as well. This issues shouldn't occur any more.
