### ISSUE TITLE
not clear how to update recipients for many secrets at once

### ISSUE THREAD

**Issue by FlorinAndrei** [justwatchcom/gopass#93]
(documentation bug)

1. Initialize a store with `gopass init my@email.adress`

2. Add a secret `gopass insert some/secret`

3. Add a recipient `gopass recipients add XXXXXXXX`

4. Add another secret `gopass insert some/othersecret`

The first secret can be decrypted by the initial recipient. The second secret can be decrypted by both recipients.

How to mass-edit many secrets at once and add / remove recipients to / from all of them?

**Comment by dominikschulz** [comment]
This sounds rather like an implementation bug. Adding a new recipient should re-encrypt all existing secrets for the new recipient.

**Comment by KamilLelonek** [comment]
What is the status here?

**Comment by dominikschulz** [comment]
Actually I think this should be fixed. I did some testing while working on #327 #328 and #329 
Encrypting all existing secrets for the new recipient(s) worked pretty flawless.
