### ISSUE TITLE
Different encryption keys for sub-directories?

### ISSUE THREAD

**Issue by stefan2904** [justwatchcom/gopass#95]
In `pass`, it is possible to use different keys to encrypt secrets by having multiple `.gpg-id` files in sub directories.

From `pass` [manpage](https://git.zx2c4.com/password-store/about/):

`Contains the default gpg key identification used for encryption and decryption. Multiple gpg keys may be specified in this file, one per line. If this file exists in any sub directories, passwords inside those sub directories are encrypted using those keys. This should be set using the init command.`

This seems not to be the case with `gopass`, is that correct?

**What I did:**

* init store with gpg key A -> key A is in ~/.password-store/.gpg-id
* create secret foo/bar
* secret is encrypted to key A
* create folder asdf
* put key B into ~/.password-store/asdf/.gpg-id
* create secret asdf/bla
* secret is encrypted to key A
* _expected: secret is encrypted to key B_

**Comment by metalmatze** [comment]
Nope. This is not yet supported, but we are talking about something like this since day one of working on gopass!

**Comment by stefan2904** [comment]
Is this talking documented somewhere / are there any hard reasons for not doing it?
(I assume the way you handle sub-stores in contrast to `pass` makes some things different.)

**Comment by dominikschulz** [comment]
We implemented the sub-store feature long before pass supported different .gpg-id files. Currently I have no plans to support that as it collides with the sub-store feature.

But if someone comes up with a clean way to handle multiple .gpg-ids in the same store, we'd will consider to support that.

**Comment by stefan2904** [comment]
I understand the conflict with the substore feature.

On the other hand, this kills your "Be 100% pass compatible" roadmap point in your README, right? :(
(2 people using a pass store, one using `pass`, the other `gopass`.)

**Comment by dominikschulz** [comment]
No, this doesn't kill our roadmap, since we never promised to *stay* _100% pass compatible_. As explained in #137 we aimed for full `pass` compatibility when releasing `gopass`. Since then `pass` and `gopass` have evolved indepently some features can and will diverge.

**Comment by stefan2904** [comment]
I guess this is a duplicate of #498 and fixed/implemented in #703
