### ISSUE TITLE
Create AppVeyor config

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#96]
We should build upon the work in #91 and create an `.appveyor.yml`.

https://gist.github.com/majkinetor/857a59ebbb43c6e687cf11d724209a21
https://www.appveyor.com/docs/build-configuration/

**Comment by AnomalRoil** [comment]
For now, it may be best to disable AppVeyor, since it's completely broken and marks valid pull request as broken, even if they are perfectly fine, passing all CI tests for linux. 

Could you consider letting it disabled until the AppVeyor config has been correctly created?

**Comment by muesli** [comment]
Work-in-progress branch here: https://github.com/muesli/gopass/tree/appveyor

**Comment by dominikschulz** [comment]
Very interesting branch. I'm looking forward to any PRs derived from that.

**Comment by dominikschulz** [comment]
Closed by #442
