### ISSUE TITLE
Improve onboarding

### ISSUE THREAD

**Issue by dominikschulz** [justwatchcom/gopass#97]
We should improve the onboarding of new users. At the moment it can be hard to set up a new store, depending on the exact use-case.

We could provide a command like `gopass setup` which will guide a new user through the whole setup of a new gopass installation.

## Example

```
$> gopass setup
Do you want to use easy mode? [Yn] n
Do you want to create a new local store? [Yn] n
Do you want to clone a remote? [Yn] y
Do you want to AutoPush commits? [Yn] y
Do you want to AutoPull changes? [Yn] y
Do you want to always trust keys when encrypting? [Yn] y
Do you want to persist keys in the store? [Yn] y
```

# Use Cases

We should account for and test at least these use cases.

1. New User, No existing Store, No GPG Keys
1. New User, No existing Store, Has GPG Keys
1. New User, Existing remote Store, No GPG Keys
1. New User, Existing remote Store, Has GPG Keys
1. Existing User, Existing local Store, Has Keys
1. Existing User, Existing local Store & new remote Store, Has Keys

**Comment by jonfujita** [comment]
@dominikschulz Looking for help with this? I'm completely new to this. I could provide an objective perspective.
